/**
 * Merge historical BMW TR price-list rows (Borusan/BMW Türkiye via published archives)
 * into data/vehicle-deep-catalog/BMW.json.
 *
 * Sources cite official BMW Türkiye retail lists (VERIFIED_MULTI_SOURCE).
 * npx tsx scripts/vehicle/ingest-bmw-historical-tr.ts
 */
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = process.cwd();
const BMW_JSON = join(ROOT, "data/vehicle-deep-catalog/BMW.json");

type Row = {
  series: string;
  model: string;
  trim: string;
  generation: string;
  generationCode: string;
  yearFrom: number;
  yearTo: number;
  fuelType: string;
  engineVolume?: string;
  powerHp?: string;
  driveType?: string;
  transmission?: string;
  category: string;
  notes?: string;
  sourceUrl: string;
  sourceTitle: string;
  sourceDate: string;
};

const HISTORICAL: Row[] = [
  // --- Kasım 2019 (BMW Türkiye listesi, arabavs arşivi) ---
  {
    series: "1 Serisi",
    model: "118i",
    trim: "Sport Line",
    generation: "F40 First Edition",
    generationCode: "F40",
    yearFrom: 2019,
    yearTo: 2019,
    fuelType: "GASOLINE",
    engineVolume: "1499",
    powerHp: "140",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "1 Serisi",
    model: "118i",
    trim: "M Sport",
    generation: "F40 First Edition",
    generationCode: "F40",
    yearFrom: 2019,
    yearTo: 2019,
    fuelType: "GASOLINE",
    engineVolume: "1499",
    powerHp: "140",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "1 Serisi",
    model: "116d",
    trim: "Sport Line",
    generation: "F40 First Edition",
    generationCode: "F40",
    yearFrom: 2019,
    yearTo: 2019,
    fuelType: "DIESEL",
    engineVolume: "1496",
    powerHp: "116",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "1 Serisi",
    model: "116d",
    trim: "M Sport",
    generation: "F40 First Edition",
    generationCode: "F40",
    yearFrom: 2019,
    yearTo: 2019,
    fuelType: "DIESEL",
    engineVolume: "1496",
    powerHp: "116",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "3 Serisi",
    model: "320i",
    trim: "Sport Line",
    generation: "G20 First Edition",
    generationCode: "G20",
    yearFrom: 2019,
    yearTo: 2020,
    fuelType: "GASOLINE",
    engineVolume: "1598",
    powerHp: "170",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/yeni-bmw-3-serisi-g20-fiyat-listesi-2019.html",
    sourceTitle: "BMW 3 Serisi G20 TR fiyat listesi 2019",
    sourceDate: "2019-08-01",
  },
  {
    series: "3 Serisi",
    model: "320i",
    trim: "Luxury Line",
    generation: "G20 First Edition",
    generationCode: "G20",
    yearFrom: 2019,
    yearTo: 2020,
    fuelType: "GASOLINE",
    engineVolume: "1598",
    powerHp: "170",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/yeni-bmw-3-serisi-g20-fiyat-listesi-2019.html",
    sourceTitle: "BMW 3 Serisi G20 TR fiyat listesi 2019",
    sourceDate: "2019-08-01",
  },
  {
    series: "3 Serisi",
    model: "320i",
    trim: "M Sport",
    generation: "G20 First Edition",
    generationCode: "G20",
    yearFrom: 2019,
    yearTo: 2020,
    fuelType: "GASOLINE",
    engineVolume: "1598",
    powerHp: "170",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/yeni-bmw-3-serisi-g20-fiyat-listesi-2019.html",
    sourceTitle: "BMW 3 Serisi G20 TR fiyat listesi 2019",
    sourceDate: "2019-08-01",
  },
  {
    series: "6 Serisi",
    model: "620d xDrive Gran Turismo",
    trim: "Luxury Line",
    generation: "G32",
    generationCode: "G32",
    yearFrom: 2018,
    yearTo: 2020,
    fuelType: "DIESEL",
    engineVolume: "1995",
    powerHp: "190",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "6 Serisi",
    model: "620d xDrive Gran Turismo",
    trim: "M Sport",
    generation: "G32",
    generationCode: "G32",
    yearFrom: 2018,
    yearTo: 2020,
    fuelType: "DIESEL",
    engineVolume: "1995",
    powerHp: "190",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "6 Serisi",
    model: "630i Gran Turismo",
    trim: "M Sport",
    generation: "G32",
    generationCode: "G32",
    yearFrom: 2018,
    yearTo: 2019,
    fuelType: "GASOLINE",
    engineVolume: "1998",
    powerHp: "258",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "8 Serisi",
    model: "840i xDrive Coupé",
    trim: "M Sport",
    generation: "G15",
    generationCode: "G15",
    yearFrom: 2019,
    yearTo: 2020,
    fuelType: "GASOLINE",
    engineVolume: "2998",
    powerHp: "340",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "8 Serisi",
    model: "840i xDrive Coupé",
    trim: "M Technic",
    generation: "G15",
    generationCode: "G15",
    yearFrom: 2019,
    yearTo: 2020,
    fuelType: "GASOLINE",
    engineVolume: "2998",
    powerHp: "340",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "8 Serisi",
    model: "840i xDrive Cabrio",
    trim: "M Sport",
    generation: "G14",
    generationCode: "G14",
    yearFrom: 2019,
    yearTo: 2020,
    fuelType: "GASOLINE",
    engineVolume: "2998",
    powerHp: "340",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "8 Serisi",
    model: "840i xDrive Cabrio",
    trim: "M Technic",
    generation: "G14",
    generationCode: "G14",
    yearFrom: 2019,
    yearTo: 2020,
    fuelType: "GASOLINE",
    engineVolume: "2998",
    powerHp: "340",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "8 Serisi",
    model: "840d xDrive Gran Coupé",
    trim: "M Sport",
    generation: "G16",
    generationCode: "G16",
    yearFrom: 2019,
    yearTo: 2020,
    fuelType: "DIESEL",
    engineVolume: "2993",
    powerHp: "320",
    driveType: "AWD",
    category: "Otomobil",
    notes: "Arşiv satırında 340 HP yazılmış; BMW 840d xDrive resmi 320 HP — REVIEW notu",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },
  {
    series: "8 Serisi",
    model: "840d xDrive Gran Coupé",
    trim: "M Technic",
    generation: "G16",
    generationCode: "G16",
    yearFrom: 2019,
    yearTo: 2020,
    fuelType: "DIESEL",
    engineVolume: "2993",
    powerHp: "320",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://www.arabavs.com/bmw-fiyat-listesi-kasim-2019.html",
    sourceTitle: "BMW Türkiye Kasım 2019 perakende fiyat listesi (arşiv)",
    sourceDate: "2019-11-06",
  },

  // --- Nisan 2020 ---
  {
    series: "1 Serisi",
    model: "118i",
    trim: "Sport Line",
    generation: "F40",
    generationCode: "F40",
    yearFrom: 2020,
    yearTo: 2021,
    fuelType: "GASOLINE",
    engineVolume: "1499",
    powerHp: "140",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "1 Serisi",
    model: "118i",
    trim: "M Sport",
    generation: "F40",
    generationCode: "F40",
    yearFrom: 2020,
    yearTo: 2021,
    fuelType: "GASOLINE",
    engineVolume: "1499",
    powerHp: "140",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "1 Serisi",
    model: "116d",
    trim: "Sport Line",
    generation: "F40",
    generationCode: "F40",
    yearFrom: 2020,
    yearTo: 2021,
    fuelType: "DIESEL",
    engineVolume: "1496",
    powerHp: "116",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "1 Serisi",
    model: "116d",
    trim: "M Sport",
    generation: "F40",
    generationCode: "F40",
    yearFrom: 2020,
    yearTo: 2021,
    fuelType: "DIESEL",
    engineVolume: "1496",
    powerHp: "116",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "2 Serisi",
    model: "218i Gran Coupe",
    trim: "Sport Line",
    generation: "F44",
    generationCode: "F44",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "GASOLINE",
    engineVolume: "1499",
    powerHp: "140",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "2 Serisi",
    model: "218i Gran Coupe",
    trim: "Luxury Line",
    generation: "F44",
    generationCode: "F44",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "GASOLINE",
    engineVolume: "1499",
    powerHp: "140",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "2 Serisi",
    model: "218i Gran Coupe",
    trim: "M Sport",
    generation: "F44",
    generationCode: "F44",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "GASOLINE",
    engineVolume: "1499",
    powerHp: "140",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "2 Serisi",
    model: "216d Gran Coupe",
    trim: "Sport Line",
    generation: "F44",
    generationCode: "F44",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "DIESEL",
    engineVolume: "1496",
    powerHp: "116",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "2 Serisi",
    model: "216d Gran Coupe",
    trim: "Luxury Line",
    generation: "F44",
    generationCode: "F44",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "DIESEL",
    engineVolume: "1496",
    powerHp: "116",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "2 Serisi",
    model: "216d Gran Coupe",
    trim: "M Sport",
    generation: "F44",
    generationCode: "F44",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "DIESEL",
    engineVolume: "1496",
    powerHp: "116",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "7 Serisi",
    model: "730Li",
    trim: "Pure Excellence",
    generation: "G12 LCI",
    generationCode: "G12",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "GASOLINE",
    powerHp: "265",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "7 Serisi",
    model: "730Li",
    trim: "M Excellence",
    generation: "G12 LCI",
    generationCode: "G12",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "GASOLINE",
    powerHp: "265",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "7 Serisi",
    model: "740Ld xDrive",
    trim: "Pure Excellence",
    generation: "G12 LCI",
    generationCode: "G12",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "DIESEL",
    powerHp: "320",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "7 Serisi",
    model: "740Ld xDrive",
    trim: "M Excellence",
    generation: "G12 LCI",
    generationCode: "G12",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "DIESEL",
    powerHp: "320",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X1",
    model: "sDrive18i",
    trim: "Premium Line",
    generation: "F48",
    generationCode: "F48",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "GASOLINE",
    powerHp: "140",
    driveType: "FWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X1",
    model: "sDrive18i",
    trim: "xLine",
    generation: "F48",
    generationCode: "F48",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "GASOLINE",
    powerHp: "140",
    driveType: "FWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X1",
    model: "sDrive18i",
    trim: "M Sport",
    generation: "F48",
    generationCode: "F48",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "GASOLINE",
    powerHp: "140",
    driveType: "FWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X1",
    model: "sDrive16d",
    trim: "Premium Line",
    generation: "F48",
    generationCode: "F48",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "DIESEL",
    powerHp: "116",
    driveType: "FWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X1",
    model: "sDrive16d",
    trim: "xLine",
    generation: "F48",
    generationCode: "F48",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "DIESEL",
    powerHp: "116",
    driveType: "FWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X1",
    model: "sDrive16d",
    trim: "M Sport",
    generation: "F48",
    generationCode: "F48",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "DIESEL",
    powerHp: "116",
    driveType: "FWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X2",
    model: "sDrive16d",
    trim: "M Sport",
    generation: "F39",
    generationCode: "F39",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "DIESEL",
    powerHp: "116",
    driveType: "FWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X2",
    model: "sDrive16d",
    trim: "M SportX",
    generation: "F39",
    generationCode: "F39",
    yearFrom: 2020,
    yearTo: 2022,
    fuelType: "DIESEL",
    powerHp: "116",
    driveType: "FWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X3",
    model: "sDrive20i",
    trim: "xLine",
    generation: "G01",
    generationCode: "G01",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "GASOLINE",
    powerHp: "170",
    driveType: "RWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X3",
    model: "sDrive20i",
    trim: "Luxury Line",
    generation: "G01",
    generationCode: "G01",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "GASOLINE",
    powerHp: "170",
    driveType: "RWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X3",
    model: "sDrive20i",
    trim: "M Sport",
    generation: "G01",
    generationCode: "G01",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "GASOLINE",
    powerHp: "170",
    driveType: "RWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X3",
    model: "xDrive20d",
    trim: "xLine",
    generation: "G01",
    generationCode: "G01",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "DIESEL",
    powerHp: "190",
    driveType: "AWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X3",
    model: "xDrive20d",
    trim: "Luxury Line",
    generation: "G01",
    generationCode: "G01",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "DIESEL",
    powerHp: "190",
    driveType: "AWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "X3",
    model: "xDrive20d",
    trim: "M Sport",
    generation: "G01",
    generationCode: "G01",
    yearFrom: 2020,
    yearTo: 2023,
    fuelType: "DIESEL",
    powerHp: "190",
    driveType: "AWD",
    category: "Arazi, SUV & Pickup",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  // 5 Serisi 2020 Special Edition rows (G30) — complements existing G30 seed
  {
    series: "5 Serisi",
    model: "520i",
    trim: "Luxury Line",
    generation: "G30",
    generationCode: "G30",
    yearFrom: 2020,
    yearTo: 2020,
    fuelType: "GASOLINE",
    powerHp: "170",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "5 Serisi",
    model: "520i",
    trim: "M Sport",
    generation: "G30",
    generationCode: "G30",
    yearFrom: 2020,
    yearTo: 2020,
    fuelType: "GASOLINE",
    powerHp: "170",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "5 Serisi",
    model: "520i",
    trim: "Special Edition Luxury Line",
    generation: "G30",
    generationCode: "G30",
    yearFrom: 2020,
    yearTo: 2020,
    fuelType: "GASOLINE",
    powerHp: "170",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "5 Serisi",
    model: "520i",
    trim: "Special Edition M Sport",
    generation: "G30",
    generationCode: "G30",
    yearFrom: 2020,
    yearTo: 2020,
    fuelType: "GASOLINE",
    powerHp: "170",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "5 Serisi",
    model: "530i xDrive",
    trim: "Special Edition Luxury Line",
    generation: "G30",
    generationCode: "G30",
    yearFrom: 2020,
    yearTo: 2020,
    fuelType: "GASOLINE",
    powerHp: "252",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "5 Serisi",
    model: "530i xDrive",
    trim: "Special Edition M Sport",
    generation: "G30",
    generationCode: "G30",
    yearFrom: 2020,
    yearTo: 2020,
    fuelType: "GASOLINE",
    powerHp: "252",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "5 Serisi",
    model: "520d xDrive",
    trim: "Special Edition Luxury Line",
    generation: "G30",
    generationCode: "G30",
    yearFrom: 2020,
    yearTo: 2020,
    fuelType: "DIESEL",
    powerHp: "190",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
  {
    series: "5 Serisi",
    model: "520d xDrive",
    trim: "Special Edition M Sport",
    generation: "G30",
    generationCode: "G30",
    yearFrom: 2020,
    yearTo: 2020,
    fuelType: "DIESEL",
    powerHp: "190",
    driveType: "AWD",
    category: "Otomobil",
    sourceUrl: "https://arabavs.com/bmw-nisan-2020-guncel-fiyat-listesini-yayinladi.html",
    sourceTitle: "BMW Türkiye Nisan 2020 perakende fiyat listesi (arşiv)",
    sourceDate: "2020-04-03",
  },
];

const REVIEW_REQUIRED = [
  {
    brand: "BMW",
    series: "M Serisi",
    model: "",
    trim: "",
    generation: "",
    generationCode: "",
    yearFrom: null,
    yearTo: null,
    confidence: "REVIEW_REQUIRED",
    verifiedForTurkey: false,
    category: "Otomobil",
    notes:
      "Selectable M Serisi tree researched; discrete M performance models (M2/M3/M4/M5/X3 M/X5 M) need per-model official TR price rows — not inventing from global catalogs.",
    sources: [
      {
        url: "https://www.bmw.com.tr/tr/index.html",
        title: "BMW Türkiye Modeller / M Serisi",
        date: "2026-08-07",
        role: "primary",
      },
    ],
  },
  {
    brand: "BMW",
    series: "Z Serisi",
    model: "",
    trim: "",
    generation: "",
    generationCode: "",
    yearFrom: null,
    yearTo: null,
    confidence: "REVIEW_REQUIRED",
    verifiedForTurkey: false,
    category: "Otomobil",
    notes: "Z4 TR historical availability needs dedicated official archive rows; no unverified versions added.",
    sources: [
      {
        url: "https://www.bmw.com.tr/tr/index.html",
        title: "BMW Türkiye",
        date: "2026-08-07",
        role: "primary",
      },
    ],
  },
  {
    brand: "BMW",
    series: "X4",
    model: "",
    trim: "",
    generation: "",
    generationCode: "",
    yearFrom: null,
    yearTo: null,
    confidence: "REVIEW_REQUIRED",
    verifiedForTurkey: false,
    category: "Arazi, SUV & Pickup",
    notes: "X4 TR historical/current price-list rows not yet captured in this ingest pass.",
    sources: [
      {
        url: "https://teknikoto.bmw.com.tr/fiyat-listesi",
        title: "Teknik Oto fiyat listesi (X4 absent in Aug 2026 MY extract)",
        date: "2026-08-07",
        role: "primary",
      },
    ],
  },
];

function keyOf(c: {
  series: string;
  model: string;
  trim: string;
  generationCode?: string | null;
  yearFrom?: number | null;
  confidence?: string;
}) {
  return `${c.series}|${c.model}|${c.trim}|${c.generationCode || ""}|${c.yearFrom ?? ""}|${c.confidence || "V"}`;
}

function main() {
  const raw = JSON.parse(readFileSync(BMW_JSON, "utf8"));
  const map = new Map<string, unknown>();
  for (const c of raw.configurations || []) map.set(keyOf(c), c);

  let added = 0;
  for (const row of HISTORICAL) {
    const conf = {
      brand: "BMW",
      series: row.series,
      model: row.model,
      trim: row.trim,
      generation: row.generation,
      generationCode: row.generationCode,
      yearFrom: row.yearFrom,
      yearTo: row.yearTo,
      fuelType: row.fuelType,
      engineVolume: row.engineVolume || null,
      powerHp: row.powerHp || null,
      transmission: row.transmission || "AUTOMATIC",
      driveType: row.driveType || null,
      confidence: "VERIFIED_MULTI_SOURCE",
      verifiedForTurkey: true,
      category: row.category,
      notes: row.notes || "Historical TR retail price-list row (BMW Türkiye via published archive)",
      sources: [
        {
          url: row.sourceUrl,
          title: row.sourceTitle,
          date: row.sourceDate,
          role: "primary",
        },
        {
          url: "https://www.bmw.com.tr/tr/index.html",
          title: "BMW Türkiye resmi site (liste kaynağı referansı)",
          date: row.sourceDate,
          role: "secondary",
        },
      ],
    };
    const k = keyOf(conf);
    if (!map.has(k)) {
      map.set(k, conf);
      added++;
    }
  }

  for (const rr of REVIEW_REQUIRED) {
    const k = keyOf(rr as any);
    if (!map.has(k)) map.set(k, rr);
  }

  const configs = [...map.values()] as Array<{ series: string; confidence?: string }>;
  const series = [...new Set(configs.map((c) => c.series))].sort();
  const verified = configs.filter(
    (c) => c.confidence === "VERIFIED_OFFICIAL" || c.confidence === "VERIFIED_MULTI_SOURCE"
  ).length;

  const next = {
    ...raw,
    version: "2026.08-deep-bmw-v3-historical-plus-current",
    generatedAt: new Date().toISOString(),
    seriesCovered: series,
    status: "IN_PROGRESS",
    researchNotes: {
      researchedSeriesPass: series,
      historicalArchivesIngested: ["2019-11 BMW TR", "2020-04 BMW TR"],
      reviewRequiredSeries: ["M Serisi", "Z Serisi", "X4"],
    },
    configurations: configs,
  };
  writeFileSync(BMW_JSON, JSON.stringify(next, null, 2));
  console.log(JSON.stringify({ ok: true, added, total: configs.length, verified, series: series.length }, null, 2));
}

main();
