/**
 * Expand Mercedes-Benz deep catalog from official TR price portal + published archives.
 * Package trim "AMG" on TR price rows is normalized to "AMG Line".
 * Mercedes-AMG performance models (C 43 / C 63 / etc.) stay as distinct model/version names.
 *
 * npx tsx scripts/vehicle/ingest-mercedes-tr.ts
 */
import { writeFileSync } from "fs";
import { join } from "path";

const OUT = join(process.cwd(), "data/vehicle-deep-catalog/Mercedes-Benz.json");

type Source = { url: string; title: string; date: string; role: string };
type Conf = {
  brand: string;
  series: string;
  model: string;
  trim: string;
  generation: string;
  generationCode: string;
  yearFrom: number | null;
  yearTo: number | null;
  fuelType?: string;
  engineVolume?: string;
  powerHp?: string;
  transmission?: string;
  driveType?: string;
  confidence: string;
  verifiedForTurkey: boolean;
  category: string;
  notes?: string;
  sources: Source[];
};

const S = {
  officialC: {
    url: "https://fiyat.mercedes-benz.com.tr/model/c-serisi-sedan/fiyat/2026",
    title: "Mercedes-Benz Türkiye resmi C-Serisi Sedan fiyat listesi MY2026",
    date: "2026-03-01",
    role: "primary",
  } as Source,
  officialE: {
    url: "https://fiyat.mercedes-benz.com.tr/model/e-serisi/fiyat/2026",
    title: "Mercedes-Benz Türkiye resmi E-Serisi fiyat listesi MY2026",
    date: "2026-04-01",
    role: "primary",
  } as Source,
  officialGlc: {
    url: "https://fiyat.mercedes-benz.com.tr/model/glc/fiyat/2026",
    title: "Mercedes-Benz Türkiye resmi GLC fiyat listesi MY2026",
    date: "2026-03-01",
    role: "primary",
  } as Source,
  officialGlcCoupe: {
    url: "https://fiyat.mercedes-benz.com.tr/model/glc-coupe/fiyat/2026",
    title: "Mercedes-Benz Türkiye resmi GLC Coupé fiyat listesi MY2026",
    date: "2026-03-01",
    role: "primary",
  } as Source,
  officialCla: {
    url: "https://fiyat.mercedes-benz.com.tr/model/cla/fiyat/2026",
    title: "Mercedes-Benz Türkiye resmi CLA fiyat listesi MY2026",
    date: "2026-05-06",
    role: "primary",
  } as Source,
  officialGla: {
    url: "https://fiyat.mercedes-benz.com.tr/model/gla-fl/fiyat/2026",
    title: "Mercedes-Benz Türkiye resmi GLA fiyat listesi MY2026",
    date: "2026-03-01",
    role: "primary",
  } as Source,
  officialEqa: {
    url: "https://fiyat.mercedes-benz.com.tr/model/eqa-fl/fiyat/2026",
    title: "Mercedes-Benz Türkiye resmi EQA fiyat listesi MY2026",
    date: "2026-03-01",
    role: "primary",
  } as Source,
  officialEqe: {
    url: "https://fiyat.mercedes-benz.com.tr/model/eqe/fiyat/2026",
    title: "Mercedes-Benz Türkiye resmi EQE fiyat listesi MY2026",
    date: "2026-03-01",
    role: "primary",
  } as Source,
  officialEqs: {
    url: "https://fiyat.mercedes-benz.com.tr/model/eqs/fiyat/2026",
    title: "Mercedes-Benz Türkiye resmi EQS fiyat listesi MY2026",
    date: "2026-03-01",
    role: "primary",
  } as Source,
  officialGle: {
    url: "https://fiyat.mercedes-benz.com.tr/model/gle/fiyat/2026",
    title: "Mercedes-Benz Türkiye resmi GLE fiyat listesi MY2026",
    date: "2026-05-06",
    role: "primary",
  } as Source,
  officialG: {
    url: "https://fiyat.mercedes-benz.com.tr/model/g-serisi/fiyat/2026",
    title: "Mercedes-Benz Türkiye resmi G-Serisi fiyat listesi MY2026",
    date: "2026-03-01",
    role: "primary",
  } as Source,
  webteknoAug: {
    url: "https://www.webtekno.com/agustos-2026-mercedes-benz-fiyat-listesi-aciklandi-bu-arabanin-sadece-vergisi-28-milyon-tl-h221719.html",
    title: "Mercedes-Benz Ağustos 2026 fiyat listesi (MB TR PDF kaynaklı yayım)",
    date: "2026-08-05",
    role: "primary",
  } as Source,
  dhAug: {
    url: "https://www.donanimhaber.com/mercedes-fiyat-listesi-sifir-mercedes-araba-fiyatlari--173368",
    title: "DonanımHaber Mercedes Ağustos 2026 fiyat listesi",
    date: "2026-08-01",
    role: "secondary",
  } as Source,
  onedioMay24: {
    url: "https://onedio.com/haber/mercedes-fiyat-listesi-mayis-2024-mercedes-a-b-c-ve-yeni-e-serisi-guncel-fiyatlari-1221701",
    title: "Mercedes Mayıs 2024 TR fiyat listesi (MB TR kaynaklı)",
    date: "2024-05-10",
    role: "primary",
  } as Source,
  otomobilirOct24: {
    url: "https://www.otomobilir.com/mercedes-benz-ekim-2024-fiyat/",
    title: "Mercedes-Benz Ekim 2024 fiyat listesi arşivi",
    date: "2024-10-01",
    role: "primary",
  } as Source,
  c2021: {
    url: "https://www.oopscars.com/2021-ocak-mercedes-benz-c-serisi-fiyat-listesi-ne-oldu/",
    title: "Mercedes-Benz C Serisi Ocak 2021 TR fiyat listesi (arşiv)",
    date: "2021-01-01",
    role: "primary",
  } as Source,
  mbHome: {
    url: "https://www.mercedes-benz.com.tr/",
    title: "Mercedes-Benz Türkiye resmi site",
    date: "2026-08-07",
    role: "secondary",
  } as Source,
  mbFiyat: {
    url: "https://fiyat.mercedes-benz.com.tr/model",
    title: "Mercedes-Benz Türkiye resmi fiyat portalı",
    date: "2026-08-07",
    role: "secondary",
  } as Source,
  mbPressAug: {
    url: "https://medya.mercedes-benz.com.tr/mercedes-benzden-agustos-ayi-finansman-kampanyalari/",
    title: "Mercedes-Benz TR Ağustos finansman kampanyaları (model adları)",
    date: "2026-08-01",
    role: "secondary",
  } as Source,
};

const AMG_LINE_NOTE =
  "TR resmi/yayımlanan fiyat satırında paket 'AMG' yazar; katalogda AMG Line paketi olarak normalize edildi (Mercedes-AMG performans modeli değil).";

function row(
  partial: Omit<Conf, "brand" | "verifiedForTurkey"> & { verifiedForTurkey?: boolean }
): Conf {
  const { verifiedForTurkey, ...rest } = partial;
  return {
    brand: "Mercedes-Benz",
    ...rest,
    verifiedForTurkey: verifiedForTurkey ?? true,
  };
}

const configurations: Conf[] = [
  // ========== A Serisi ==========
  row({
    series: "A Serisi",
    model: "A 200",
    trim: "AMG Line",
    generation: "W177 MY2026",
    generationCode: "W177",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1332",
    powerHp: "163",
    transmission: "AUTOMATIC",
    driveType: "FWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Aug 2026 TR: A 200 AMG 7G-DCT. ${AMG_LINE_NOTE}`,
    sources: [S.webteknoAug, S.dhAug, S.mbHome],
  }),
  row({
    series: "A Serisi",
    model: "Mercedes-AMG A 45 S 4MATIC+",
    trim: "Performance",
    generation: "W177 MY2026",
    generationCode: "W177",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1991",
    powerHp: "421",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Aug 2026 DH: AMG A 45 S 4MATIC+ — Mercedes-AMG performans modeli",
    sources: [S.dhAug, S.webteknoAug],
  }),
  row({
    series: "A Serisi",
    model: "A 200",
    trim: "AMG Line",
    generation: "W177",
    generationCode: "W177",
    yearFrom: 2023,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1332",
    powerHp: "163",
    transmission: "AUTOMATIC",
    driveType: "FWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Mayıs/Ekim 2024 TR: A 200 AMG. ${AMG_LINE_NOTE}`,
    sources: [S.onedioMay24, S.otomobilirOct24],
  }),
  row({
    series: "A Serisi",
    model: "A 200 Sedan",
    trim: "AMG Line",
    generation: "V177",
    generationCode: "V177",
    yearFrom: 2023,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1332",
    powerHp: "163",
    transmission: "AUTOMATIC",
    driveType: "FWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Ekim 2024 TR: A 200 Sedan AMG. ${AMG_LINE_NOTE}`,
    sources: [S.otomobilirOct24, S.mbHome],
  }),
  row({
    series: "A Serisi",
    model: "Mercedes-AMG A 45 S 4MATIC+",
    trim: "Performance",
    generation: "W177",
    generationCode: "W177",
    yearFrom: 2023,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1991",
    powerHp: "421",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Mayıs/Ekim 2024 TR: Mercedes-AMG A 45 S 4MATIC+ Performance",
    sources: [S.onedioMay24, S.otomobilirOct24],
  }),

  // ========== B Serisi (historical; absent from Aug 2026 current table) ==========
  row({
    series: "B Serisi",
    model: "B 200",
    trim: "Progressive",
    generation: "W247",
    generationCode: "W247",
    yearFrom: 2023,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1332",
    powerHp: "163",
    transmission: "AUTOMATIC",
    driveType: "FWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Mayıs/Ekim 2024 TR: B 200 Progressive. Aug 2026 current MY listesinde yok.",
    sources: [S.onedioMay24, S.otomobilirOct24],
  }),

  // ========== C Serisi official MY2026 ==========
  row({
    series: "C Serisi",
    model: "C 200 4MATIC",
    trim: "AMG Line",
    generation: "W206 MY2026",
    generationCode: "W206",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1496",
    powerHp: "204",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: `Official TR: C 200 4MATIC + AMG, 9G-TRONIC. ${AMG_LINE_NOTE}`,
    sources: [S.officialC, S.webteknoAug],
  }),
  row({
    series: "C Serisi",
    model: "C 200 4MATIC",
    trim: "140th Year Edition",
    generation: "W206 MY2026",
    generationCode: "W206",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1496",
    powerHp: "204",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: "Official TR special edition on C 200 4MATIC",
    sources: [S.officialC, S.webteknoAug],
  }),
  row({
    series: "C Serisi",
    model: "Mercedes-AMG C 43 4MATIC",
    trim: "Performance",
    generation: "W206 MY2026",
    generationCode: "W206",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1991",
    powerHp: "421",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: "Mercedes-AMG performans modeli — AMG Line paketinden ayrı",
    sources: [S.officialC, S.webteknoAug],
  }),
  row({
    series: "C Serisi",
    model: "Mercedes-AMG C 63 S E PERFORMANCE",
    trim: "",
    generation: "W206 MY2026",
    generationCode: "W206",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "PLUGIN_HYBRID",
    engineVolume: "1991",
    powerHp: "680",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: "Official package field '-'; identity is Mercedes-AMG version name",
    sources: [S.officialC, S.webteknoAug],
  }),
  row({
    series: "C Serisi",
    model: "C 200 4MATIC All-Terrain",
    trim: "",
    generation: "S206 All-Terrain MY2026",
    generationCode: "S206",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1496",
    powerHp: "204",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Aug 2026 TR: C 200 4MATIC All-Terrain 9G-TRONIC",
    sources: [S.webteknoAug, S.dhAug, S.mbPressAug],
  }),
  row({
    series: "C Serisi",
    model: "Mercedes-AMG C 63 S E PERFORMANCE Estate",
    trim: "",
    generation: "S206 MY2026",
    generationCode: "S206",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "PLUGIN_HYBRID",
    engineVolume: "1991",
    powerHp: "680",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Aug 2026 TR: Mercedes-AMG C 63 S E PERFORMANCE Estate",
    sources: [S.webteknoAug, S.dhAug],
  }),
  // Historical W206 packages (Avantgarde still listed 2024)
  row({
    series: "C Serisi",
    model: "C 200 4MATIC",
    trim: "Avantgarde",
    generation: "W206",
    generationCode: "W206",
    yearFrom: 2022,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1496",
    powerHp: "204",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Mayıs/Ekim 2024 TR: C 200 4MATIC Avantgarde",
    sources: [S.onedioMay24, S.otomobilirOct24],
  }),
  row({
    series: "C Serisi",
    model: "C 200 4MATIC",
    trim: "AMG Line",
    generation: "W206",
    generationCode: "W206",
    yearFrom: 2022,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1496",
    powerHp: "204",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Mayıs/Ekim 2024 TR: C 200 4MATIC AMG. ${AMG_LINE_NOTE}`,
    sources: [S.onedioMay24, S.otomobilirOct24],
  }),
  row({
    series: "C Serisi",
    model: "Mercedes-AMG C 43 4MATIC",
    trim: "Performance",
    generation: "W206",
    generationCode: "W206",
    yearFrom: 2022,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1991",
    powerHp: "408",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Mayıs/Ekim 2024 TR Mercedes-AMG C 43 4MATIC Performance",
    sources: [S.onedioMay24, S.otomobilirOct24],
  }),
  row({
    series: "C Serisi",
    model: "Mercedes-AMG C 63 S E PERFORMANCE",
    trim: "",
    generation: "W206",
    generationCode: "W206",
    yearFrom: 2023,
    yearTo: 2024,
    fuelType: "PLUGIN_HYBRID",
    engineVolume: "1991",
    powerHp: "680",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Mayıs/Ekim 2024 TR Mercedes-AMG C 63 S E PERFORMANCE",
    sources: [S.onedioMay24, S.otomobilirOct24],
  }),
  // W205 LCI 2021
  row({
    series: "C Serisi",
    model: "C 200 4MATIC",
    trim: "Exclusive",
    generation: "W205 LCI",
    generationCode: "W205",
    yearFrom: 2018,
    yearTo: 2021,
    fuelType: "GASOLINE",
    engineVolume: "1497",
    powerHp: "184",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Ocak 2021 TR: C 200 4MATIC Exclusive",
    sources: [S.c2021, S.mbHome],
  }),
  row({
    series: "C Serisi",
    model: "C 200 4MATIC",
    trim: "AMG Line",
    generation: "W205 LCI",
    generationCode: "W205",
    yearFrom: 2018,
    yearTo: 2021,
    fuelType: "GASOLINE",
    engineVolume: "1497",
    powerHp: "184",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Ocak 2021 TR: C 200 4MATIC AMG. ${AMG_LINE_NOTE}`,
    sources: [S.c2021, S.mbHome],
  }),
  row({
    series: "C Serisi",
    model: "C 200 d",
    trim: "Comfort",
    generation: "W205 LCI",
    generationCode: "W205",
    yearFrom: 2018,
    yearTo: 2021,
    fuelType: "DIESEL",
    engineVolume: "1597",
    powerHp: "160",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Ocak 2021 TR: C 200 d Comfort",
    sources: [S.c2021, S.mbHome],
  }),
  row({
    series: "C Serisi",
    model: "C 200 d",
    trim: "Exclusive",
    generation: "W205 LCI",
    generationCode: "W205",
    yearFrom: 2018,
    yearTo: 2021,
    fuelType: "DIESEL",
    engineVolume: "1597",
    powerHp: "160",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Ocak 2021 TR: C 200 d Exclusive",
    sources: [S.c2021, S.mbHome],
  }),
  row({
    series: "C Serisi",
    model: "C 200 d",
    trim: "AMG Line",
    generation: "W205 LCI",
    generationCode: "W205",
    yearFrom: 2018,
    yearTo: 2021,
    fuelType: "DIESEL",
    engineVolume: "1597",
    powerHp: "160",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Ocak 2021 TR: C 200 d AMG. ${AMG_LINE_NOTE}`,
    sources: [S.c2021, S.mbHome],
  }),

  // ========== CLA ==========
  row({
    series: "CLA",
    model: "CLA 200+",
    trim: "AMG Line",
    generation: "C174 Electric MY2026",
    generationCode: "C174",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "ELECTRIC",
    powerHp: "218",
    transmission: "AUTOMATIC",
    driveType: "FWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: `Official TR: CLA 200+ AMG electric. ${AMG_LINE_NOTE}`,
    sources: [S.officialCla, S.webteknoAug],
  }),
  row({
    series: "CLA",
    model: "CLA 220 4MATIC",
    trim: "AMG Line",
    generation: "C174 MY2026",
    generationCode: "C174",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1499",
    powerHp: "190",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: `Official TR: CLA 220 4MATIC AMG 8G-eDCT. ${AMG_LINE_NOTE}`,
    sources: [S.officialCla, S.webteknoAug],
  }),
  row({
    series: "CLA",
    model: "CLA 220 4MATIC Shooting Brake",
    trim: "AMG Line",
    generation: "X174 MY2026",
    generationCode: "X174",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1499",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Aug 2026 TR: CLA 220 4MATIC Shooting Brake AMG 8G-eDCT. ${AMG_LINE_NOTE}`,
    sources: [S.webteknoAug, S.dhAug],
  }),
  row({
    series: "CLA",
    model: "CLA 200",
    trim: "AMG Line",
    generation: "C118",
    generationCode: "C118",
    yearFrom: 2019,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1332",
    powerHp: "163",
    transmission: "AUTOMATIC",
    driveType: "FWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Mayıs 2024 TR: CLA 200 AMG (önceki nesil). ${AMG_LINE_NOTE}`,
    sources: [S.onedioMay24, S.mbHome],
  }),
  row({
    series: "CLA",
    model: "Mercedes-AMG CLA 45 S 4MATIC+",
    trim: "Performance",
    generation: "C118",
    generationCode: "C118",
    yearFrom: 2019,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1991",
    powerHp: "421",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Mayıs 2024 TR: Mercedes-AMG CLA 45 S 4MATIC+ Performance",
    sources: [S.onedioMay24, S.mbHome],
  }),

  // ========== CLE ==========
  row({
    series: "CLE",
    model: "CLE 300 4MATIC Coupé",
    trim: "AMG Line",
    generation: "C236 MY2026",
    generationCode: "C236",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1999",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Aug 2026 TR: CLE 300 4MATIC Coupé AMG 9G-TRONIC. ${AMG_LINE_NOTE}`,
    sources: [S.webteknoAug, S.dhAug],
  }),
  row({
    series: "CLE",
    model: "Mercedes-AMG CLE 53 4MATIC+",
    trim: "Performance",
    generation: "C236 MY2026",
    generationCode: "C236",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "2999",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Aug 2026 TR: Mercedes-AMG CLE 53 4MATIC+ Performance",
    sources: [S.webteknoAug, S.dhAug],
  }),
  row({
    series: "CLE",
    model: "CLE 300 4MATIC Cabriolet",
    trim: "AMG Line",
    generation: "A236 MY2026",
    generationCode: "A236",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1999",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Aug 2026 TR: CLE 300 4MATIC Cabriolet AMG. ${AMG_LINE_NOTE}`,
    sources: [S.webteknoAug, S.dhAug],
  }),

  // ========== E Serisi ==========
  row({
    series: "E Serisi",
    model: "E 180",
    trim: "Exclusive",
    generation: "W214 MY2026",
    generationCode: "W214",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1496",
    powerHp: "170",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: "Official TR: E 180 Exclusive 9G-TRONIC",
    sources: [S.officialE, S.webteknoAug],
  }),
  row({
    series: "E Serisi",
    model: "E 180",
    trim: "AMG Line",
    generation: "W214 MY2026",
    generationCode: "W214",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1496",
    powerHp: "170",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: `Official TR: E 180 AMG. ${AMG_LINE_NOTE}`,
    sources: [S.officialE, S.webteknoAug],
  }),
  row({
    series: "E Serisi",
    model: "E 220 d 4MATIC",
    trim: "Exclusive",
    generation: "W214 MY2026",
    generationCode: "W214",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "DIESEL",
    engineVolume: "1993",
    powerHp: "197",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: "Official TR: E 220 d 4MATIC Exclusive 9G-TRONIC",
    sources: [S.officialE, S.webteknoAug],
  }),
  row({
    series: "E Serisi",
    model: "E 220 d 4MATIC",
    trim: "AMG Line",
    generation: "W214 MY2026",
    generationCode: "W214",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "DIESEL",
    engineVolume: "1993",
    powerHp: "197",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: `Official TR: E 220 d 4MATIC AMG. ${AMG_LINE_NOTE}`,
    sources: [S.officialE, S.webteknoAug],
  }),
  row({
    series: "E Serisi",
    model: "Mercedes-AMG E 53 Hybrid 4MATIC+",
    trim: "Performance",
    generation: "W214 MY2026",
    generationCode: "W214",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "PLUGIN_HYBRID",
    engineVolume: "2999",
    powerHp: "585",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: "Official TR: Mercedes-AMG E 53 Hybrid 4MATIC+ Performance",
    sources: [S.officialE, S.webteknoAug],
  }),
  row({
    series: "E Serisi",
    model: "E 180",
    trim: "Edition 1 Exclusive",
    generation: "W214 launch",
    generationCode: "W214",
    yearFrom: 2023,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1496",
    powerHp: "170",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Mayıs 2024 TR: Yeni E 180 Edition 1 Exclusive",
    sources: [S.onedioMay24, S.mbHome],
  }),
  row({
    series: "E Serisi",
    model: "E 180",
    trim: "Edition 1 AMG Line",
    generation: "W214 launch",
    generationCode: "W214",
    yearFrom: 2023,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1496",
    powerHp: "170",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Mayıs 2024 TR: Yeni E 180 Edition 1 AMG. ${AMG_LINE_NOTE}`,
    sources: [S.onedioMay24, S.mbHome],
  }),
  row({
    series: "E Serisi",
    model: "E 220 d 4MATIC",
    trim: "Edition 1 Exclusive",
    generation: "W214 launch",
    generationCode: "W214",
    yearFrom: 2023,
    yearTo: 2024,
    fuelType: "DIESEL",
    engineVolume: "1993",
    powerHp: "197",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Mayıs 2024 TR: Yeni E 220 d 4MATIC Edition 1 Exclusive",
    sources: [S.onedioMay24, S.mbHome],
  }),
  row({
    series: "E Serisi",
    model: "E 220 d 4MATIC",
    trim: "Edition 1 AMG Line",
    generation: "W214 launch",
    generationCode: "W214",
    yearFrom: 2023,
    yearTo: 2024,
    fuelType: "DIESEL",
    engineVolume: "1993",
    powerHp: "197",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: `Mayıs 2024 TR: Yeni E 220 d 4MATIC Edition 1 AMG. ${AMG_LINE_NOTE}`,
    sources: [S.onedioMay24, S.mbHome],
  }),

  // ========== S Serisi ==========
  row({
    series: "S Serisi",
    model: "S 450 d 4MATIC L",
    trim: "Inspiration",
    generation: "W223 MY2026",
    generationCode: "W223",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "DIESEL",
    engineVolume: "2989",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Aug 2026 TR: S 450 d 4MATIC L Inspiration 9G-TRONIC",
    sources: [S.webteknoAug, S.dhAug],
  }),
  row({
    series: "S Serisi",
    model: "S 450 d 4MATIC L",
    trim: "Inspiration",
    generation: "W223",
    generationCode: "W223",
    yearFrom: 2021,
    yearTo: 2024,
    fuelType: "DIESEL",
    engineVolume: "2989",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Mayıs 2024 TR: S 450 d 4MATIC L Inspiration",
    sources: [S.onedioMay24, S.mbHome],
  }),
  row({
    series: "S Serisi",
    model: "S 500 4MATIC L",
    trim: "Inspiration",
    generation: "W223",
    generationCode: "W223",
    yearFrom: 2021,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "2999",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Mayıs 2024 TR: S 500 4MATIC L Inspiration (Aug 2026 listesinde fiyat satırı yok)",
    sources: [S.onedioMay24, S.dhAug],
  }),
  row({
    series: "S Serisi",
    model: "Mercedes-AMG S 63 E PERFORMANCE",
    trim: "",
    generation: "W223",
    generationCode: "W223",
    yearFrom: 2023,
    yearTo: 2024,
    fuelType: "PLUGIN_HYBRID",
    engineVolume: "3982",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Mayıs 2024 TR: AMG S 63 E-PERFORMANCE",
    sources: [S.onedioMay24, S.mbHome],
  }),

  // ========== SL (Mercedes-AMG SL current) ==========
  row({
    series: "SL",
    model: "Mercedes-AMG SL 43",
    trim: "Performance",
    generation: "R232 MY2026",
    generationCode: "R232",
    yearFrom: 2022,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1991",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Aug 2026 TR: Mercedes-AMG SL 43 Performance",
    sources: [S.webteknoAug, S.dhAug],
  }),
  row({
    series: "SL",
    model: "Mercedes-AMG SL 63 4MATIC+",
    trim: "Performance",
    generation: "R232 MY2026",
    generationCode: "R232",
    yearFrom: 2022,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "3982",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Aug 2026 TR: Mercedes-AMG SL 63 4MATIC+ Performance",
    sources: [S.webteknoAug, S.dhAug],
  }),

  // ========== AMG GT ==========
  row({
    series: "AMG GT",
    model: "Mercedes-AMG GT 43",
    trim: "Performance",
    generation: "C192 MY2026",
    generationCode: "C192",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1991",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Aug 2026 TR: Mercedes-AMG GT 43 Performance",
    sources: [S.webteknoAug, S.dhAug],
  }),
  row({
    series: "AMG GT",
    model: "Mercedes-AMG GT 63 4MATIC+",
    trim: "Performance",
    generation: "C192 MY2026",
    generationCode: "C192",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "3982",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Aug 2026 TR: Mercedes-AMG GT 63 4MATIC+ Performance",
    sources: [S.webteknoAug, S.dhAug],
  }),
  row({
    series: "AMG GT",
    model: "Mercedes-AMG GT 63 PRO 4MATIC+",
    trim: "",
    generation: "C192 MY2026",
    generationCode: "C192",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "3982",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Otomobil",
    notes: "Aug 2026 TR: Mercedes-AMG GT 63 PRO 4MATIC+",
    sources: [S.webteknoAug, S.dhAug],
  }),

  // ========== GLA ==========
  row({
    series: "GLA",
    model: "GLA 200",
    trim: "AMG Line",
    generation: "H247 FL MY2026",
    generationCode: "H247",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1332",
    powerHp: "163",
    transmission: "AUTOMATIC",
    driveType: "FWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: `Official TR: GLA 200 AMG 7G-DCT. ${AMG_LINE_NOTE}`,
    sources: [S.officialGla, S.webteknoAug],
  }),
  row({
    series: "GLA",
    model: "GLA 200",
    trim: "AMG Line",
    generation: "H247",
    generationCode: "H247",
    yearFrom: 2020,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "1332",
    powerHp: "163",
    transmission: "AUTOMATIC",
    driveType: "FWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Arazi, SUV & Pickup",
    notes: `Mayıs 2024 TR: GLA 200 AMG. ${AMG_LINE_NOTE}`,
    sources: [S.onedioMay24, S.mbHome],
  }),

  // ========== GLB ==========
  row({
    series: "GLB",
    model: "GLB 200+",
    trim: "AMG Line",
    generation: "X247 new MY2026",
    generationCode: "X247",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "ELECTRIC",
    transmission: "AUTOMATIC",
    driveType: "FWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Arazi, SUV & Pickup",
    notes: `Aug 2026 TR: GLB 200+ AMG electric. ${AMG_LINE_NOTE}`,
    sources: [S.webteknoAug, S.dhAug, S.mbPressAug],
  }),
  row({
    series: "GLB",
    model: "GLB 220 4MATIC",
    trim: "AMG Line",
    generation: "X247 new MY2026",
    generationCode: "X247",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1499",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Arazi, SUV & Pickup",
    notes: `Aug 2026 TR: GLB 220 4MATIC AMG 8G-eDCT. ${AMG_LINE_NOTE}`,
    sources: [S.webteknoAug, S.dhAug, S.mbPressAug],
  }),

  // ========== GLC ==========
  row({
    series: "GLC",
    model: "GLC 180",
    trim: "AMG Line",
    generation: "X254 MY2026",
    generationCode: "X254",
    yearFrom: 2023,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1496",
    powerHp: "170",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: `Official TR: GLC 180 AMG 9G-TRONIC. ${AMG_LINE_NOTE}`,
    sources: [S.officialGlc, S.webteknoAug],
  }),
  row({
    series: "GLC",
    model: "GLC 300 d 4MATIC",
    trim: "AMG Line",
    generation: "X254 MY2026",
    generationCode: "X254",
    yearFrom: 2023,
    yearTo: 2026,
    fuelType: "DIESEL",
    engineVolume: "1993",
    powerHp: "269",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: `Official TR: GLC 300 d 4MATIC AMG. ${AMG_LINE_NOTE}`,
    sources: [S.officialGlc, S.webteknoAug],
  }),
  row({
    series: "GLC",
    model: "GLC 400 4MATIC",
    trim: "Edition 1 AMG Line",
    generation: "X254 Electric MY2026",
    generationCode: "X254",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "ELECTRIC",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Arazi, SUV & Pickup",
    notes: "Aug 2026 TR: GLC 400 4MATIC Edition 1 AMG (elektrikli). Paket satır adı normalize.",
    sources: [S.webteknoAug, S.dhAug],
  }),
  row({
    series: "GLC",
    model: "Mercedes-AMG GLC 43 4MATIC",
    trim: "Performance",
    generation: "X254 MY2026",
    generationCode: "X254",
    yearFrom: 2023,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1991",
    powerHp: "421",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: "Official TR Mercedes-AMG GLC 43 4MATIC Performance",
    sources: [S.officialGlc, S.webteknoAug],
  }),
  row({
    series: "GLC",
    model: "Mercedes-AMG GLC 63 S E PERFORMANCE",
    trim: "",
    generation: "X254 MY2026",
    generationCode: "X254",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "PLUGIN_HYBRID",
    engineVolume: "1991",
    powerHp: "680",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: "Official TR Mercedes-AMG GLC 63 S E PERFORMANCE (package '-')",
    sources: [S.officialGlc, S.webteknoAug],
  }),
  row({
    series: "GLC",
    model: "GLC 180 Coupé",
    trim: "AMG Line",
    generation: "C254 MY2026",
    generationCode: "C254",
    yearFrom: 2023,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1496",
    powerHp: "170",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: `Official TR: GLC 180 Coupé AMG. ${AMG_LINE_NOTE}`,
    sources: [S.officialGlcCoupe, S.webteknoAug],
  }),
  row({
    series: "GLC",
    model: "Mercedes-AMG GLC 43 4MATIC Coupé",
    trim: "Performance",
    generation: "C254 MY2026",
    generationCode: "C254",
    yearFrom: 2023,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "1991",
    powerHp: "421",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: "Official TR Mercedes-AMG GLC 43 4MATIC Coupé Performance",
    sources: [S.officialGlcCoupe, S.webteknoAug],
  }),
  row({
    series: "GLC",
    model: "Mercedes-AMG GLC 63 S E PERFORMANCE Coupé",
    trim: "",
    generation: "C254 MY2026",
    generationCode: "C254",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "PLUGIN_HYBRID",
    engineVolume: "1991",
    powerHp: "680",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: "Official TR Mercedes-AMG GLC 63 S E PERFORMANCE Coupé",
    sources: [S.officialGlcCoupe, S.webteknoAug],
  }),

  // ========== GLE ==========
  row({
    series: "GLE",
    model: "GLE 300 d 4MATIC",
    trim: "AMG Line",
    generation: "V167 MY2026",
    generationCode: "V167",
    yearFrom: 2023,
    yearTo: 2026,
    fuelType: "DIESEL",
    engineVolume: "1993",
    powerHp: "269",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: `Official TR: GLE 300 d 4MATIC AMG. ${AMG_LINE_NOTE}`,
    sources: [S.officialGle, S.webteknoAug],
  }),
  row({
    series: "GLE",
    model: "GLE 300 d 4MATIC Coupé",
    trim: "AMG Line",
    generation: "C167 MY2026",
    generationCode: "C167",
    yearFrom: 2023,
    yearTo: 2026,
    fuelType: "DIESEL",
    engineVolume: "1993",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Arazi, SUV & Pickup",
    notes: `Aug 2026 TR: GLE 300 d 4MATIC Coupé AMG. ${AMG_LINE_NOTE}`,
    sources: [S.webteknoAug, S.dhAug],
  }),

  // ========== GLS ==========
  row({
    series: "GLS",
    model: "GLS 450 d 4MATIC",
    trim: "AMG Line",
    generation: "X167 MY2026",
    generationCode: "X167",
    yearFrom: 2023,
    yearTo: 2026,
    fuelType: "DIESEL",
    engineVolume: "2989",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Arazi, SUV & Pickup",
    notes: `Aug 2026 TR: GLS 450 d 4MATIC AMG 9G-TRONIC. ${AMG_LINE_NOTE}`,
    sources: [S.webteknoAug, S.dhAug],
  }),

  // ========== G Serisi ==========
  row({
    series: "G Serisi",
    model: "G 450 d",
    trim: "Heritage",
    generation: "W465 MY2026",
    generationCode: "W465",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "DIESEL",
    engineVolume: "2989",
    powerHp: "367",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: "Official TR: G 450 d Heritage 9G-TRONIC",
    sources: [S.officialG, S.webteknoAug],
  }),
  row({
    series: "G Serisi",
    model: "G 500",
    trim: "Heritage",
    generation: "W465 MY2026",
    generationCode: "W465",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "2999",
    powerHp: "449",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: "Official TR: G 500 Heritage 9G-TRONIC",
    sources: [S.officialG, S.webteknoAug],
  }),
  row({
    series: "G Serisi",
    model: "G 580",
    trim: "Heritage",
    generation: "W465 Electric MY2026",
    generationCode: "W465",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "ELECTRIC",
    powerHp: "587",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: "Official TR: G 580 Heritage electric",
    sources: [S.officialG, S.webteknoAug],
  }),
  row({
    series: "G Serisi",
    model: "Mercedes-AMG G 63",
    trim: "Performance",
    generation: "W465 MY2026",
    generationCode: "W465",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "GASOLINE",
    engineVolume: "3982",
    powerHp: "585",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: "Official TR: Mercedes-AMG G 63 Performance",
    sources: [S.officialG, S.webteknoAug],
  }),
  row({
    series: "G Serisi",
    model: "G 400 d",
    trim: "Magnetic",
    generation: "W463A",
    generationCode: "W463A",
    yearFrom: 2018,
    yearTo: 2024,
    fuelType: "DIESEL",
    engineVolume: "2925",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Arazi, SUV & Pickup",
    notes: "Mayıs 2024 TR: G 400 d Magnetic (önceki nesil)",
    sources: [S.onedioMay24, S.mbHome],
  }),
  row({
    series: "G Serisi",
    model: "Mercedes-AMG G 63",
    trim: "Performance",
    generation: "W463A",
    generationCode: "W463A",
    yearFrom: 2018,
    yearTo: 2024,
    fuelType: "GASOLINE",
    engineVolume: "3982",
    powerHp: "585",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_MULTI_SOURCE",
    category: "Arazi, SUV & Pickup",
    notes: "Mayıs 2024 TR: AMG G 63 Performance",
    sources: [S.onedioMay24, S.mbHome],
  }),

  // ========== EQA / EQE / EQS ==========
  row({
    series: "EQA",
    model: "EQA 250+",
    trim: "Night Edition",
    generation: "H243 FL MY2026",
    generationCode: "H243",
    yearFrom: 2024,
    yearTo: 2026,
    fuelType: "ELECTRIC",
    powerHp: "190",
    transmission: "AUTOMATIC",
    driveType: "FWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Arazi, SUV & Pickup",
    notes: "Official TR: EQA 250+ Night Edition",
    sources: [S.officialEqa, S.webteknoAug],
  }),
  row({
    series: "EQE",
    model: "EQE 280",
    trim: "AMG Line",
    generation: "V295 MY2026",
    generationCode: "V295",
    yearFrom: 2023,
    yearTo: 2026,
    fuelType: "ELECTRIC",
    powerHp: "218",
    transmission: "AUTOMATIC",
    driveType: "RWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: `Official TR: EQE 280 AMG. ${AMG_LINE_NOTE}`,
    sources: [S.officialEqe, S.webteknoAug],
  }),
  row({
    series: "EQE",
    model: "EQE 350 4MATIC",
    trim: "AMG Line",
    generation: "V295 MY2026",
    generationCode: "V295",
    yearFrom: 2023,
    yearTo: 2026,
    fuelType: "ELECTRIC",
    powerHp: "320",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: `Official TR: EQE 350 4MATIC AMG. ${AMG_LINE_NOTE}`,
    sources: [S.officialEqe, S.webteknoAug],
  }),
  row({
    series: "EQS",
    model: "EQS 450 4MATIC",
    trim: "Inspiration",
    generation: "V297 MY2026",
    generationCode: "V297",
    yearFrom: 2022,
    yearTo: 2026,
    fuelType: "ELECTRIC",
    powerHp: "360",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: "Official TR: EQS 450 4MATIC Inspiration",
    sources: [S.officialEqs, S.webteknoAug],
  }),
  row({
    series: "EQS",
    model: "EQS 580 4MATIC",
    trim: "Heritage Edition",
    generation: "V297 MY2026",
    generationCode: "V297",
    yearFrom: 2025,
    yearTo: 2026,
    fuelType: "ELECTRIC",
    powerHp: "544",
    transmission: "AUTOMATIC",
    driveType: "AWD",
    confidence: "VERIFIED_OFFICIAL",
    category: "Otomobil",
    notes: "Official TR: EQS 580 4MATIC Heritage Edition",
    sources: [S.officialEqs, S.webteknoAug],
  }),

  // ========== REVIEW_REQUIRED / REJECTED ==========
  ...[
    {
      series: "EQB",
      category: "Arazi, SUV & Pickup",
      confidence: "REVIEW_REQUIRED",
      notes:
        "EQB TR'de geçmişte listelenmiş; Aug 2026 DH tablosunda EQB 250+/350 satırları '-' (fiyatsız). Doğrulanabilir güncel/arşiv satır yakalanmadı — icat yok.",
    },
    {
      series: "EQE SUV",
      category: "Arazi, SUV & Pickup",
      confidence: "REVIEW_REQUIRED",
      notes:
        "EQE SUV TR perakende fiyat satırı (2021–2026 arşiv + Aug 2026) doğrulanamadı; global katalogdan versiyon uydurulmadı.",
    },
    {
      series: "EQS SUV",
      category: "Arazi, SUV & Pickup",
      confidence: "REVIEW_REQUIRED",
      notes:
        "EQS SUV TR perakende fiyat satırı doğrulanamadı; Aug 2026 listesinde yalnızca EQS sedan var.",
    },
    {
      series: "CLS",
      category: "Otomobil",
      confidence: "REVIEW_REQUIRED",
      notes:
        "CLS TR'de tarihsel olarak satıldı; güncel MY listesinde yok. Arşiv Exclusive/AMG Line satırları henüz yakalanmadı.",
    },
    {
      series: "SLC",
      category: "Otomobil",
      confidence: "REVIEW_REQUIRED",
      notes: "SLC TR tarihsel roadster; resmi arşiv fiyat satırları bu geçişte doğrulanmadı.",
    },
    {
      series: "SLK",
      category: "Otomobil",
      confidence: "REVIEW_REQUIRED",
      notes: "SLK (SLC öncesi) TR tarihsel; doğrulanabilir donanım/motor satırları bekliyor.",
    },
    {
      series: "Vito",
      category: "Minivan & Panelvan",
      confidence: "REVIEW_REQUIRED",
      notes:
        "Vito/eVito ticari hat; binek fiyat portalı dışında ayrı LCV listeleri. Doğrulanabilir TR satırı eklenmedi.",
    },
    {
      series: "V Serisi",
      category: "Minivan & Panelvan",
      confidence: "REVIEW_REQUIRED",
      notes: "V-Class TR varlığı araştırıldı; bu geçişte doğrulanabilir perakende satır yakalanmadı.",
    },
  ].map((x) =>
    row({
      series: x.series,
      model: "",
      trim: "",
      generation: "",
      generationCode: "",
      yearFrom: null,
      yearTo: null,
      confidence: x.confidence,
      verifiedForTurkey: false,
      category: x.category,
      notes: x.notes,
      sources: [S.mbHome, S.mbFiyat, S.dhAug],
    })
  ),

  // Explicit REJECTED: do not invent these common false mappings
  row({
    series: "GLC",
    model: "GLC 220 d 4MATIC",
    trim: "AMG Line",
    generation: "",
    generationCode: "X254",
    yearFrom: null,
    yearTo: null,
    fuelType: "DIESEL",
    confidence: "REJECTED",
    verifiedForTurkey: false,
    category: "Arazi, SUV & Pickup",
    notes:
      "REJECTED: Aug 2026 / official MY2026 TR GLC dizel satırı GLC 300 d 4MATIC — 'GLC 220 d' TR listesinde yok; icat edilmedi.",
    sources: [S.officialGlc, S.webteknoAug],
  }),
  row({
    series: "E Serisi",
    model: "E 200",
    trim: "AMG Line",
    generation: "W214",
    generationCode: "W214",
    yearFrom: null,
    yearTo: null,
    fuelType: "GASOLINE",
    confidence: "REJECTED",
    verifiedForTurkey: false,
    category: "Otomobil",
    notes:
      "REJECTED: W214 TR giriş benzinli satırı E 180 (Exclusive/AMG). 'E 200' W214 TR listesinde doğrulanmadı.",
    sources: [S.officialE, S.webteknoAug],
  }),
  row({
    series: "CLE",
    model: "CLE 200",
    trim: "AMG Line",
    generation: "C236",
    generationCode: "C236",
    yearFrom: null,
    yearTo: null,
    fuelType: "GASOLINE",
    confidence: "REJECTED",
    verifiedForTurkey: false,
    category: "Otomobil",
    notes:
      "REJECTED: Aug 2026 TR CLE satırı CLE 300 4MATIC — 'CLE 200' TR listesinde yok.",
    sources: [S.webteknoAug, S.dhAug],
  }),
  row({
    series: "GLS",
    model: "GLS 450 4MATIC",
    trim: "AMG Line",
    generation: "X167",
    generationCode: "X167",
    yearFrom: null,
    yearTo: null,
    fuelType: "GASOLINE",
    confidence: "REJECTED",
    verifiedForTurkey: false,
    category: "Arazi, SUV & Pickup",
    notes:
      "REJECTED: Aug 2026 TR satırı GLS 450 d 4MATIC (dizel) — benzinli 'GLS 450' doğrulanmadı.",
    sources: [S.webteknoAug, S.dhAug],
  }),
  row({
    series: "EQE",
    model: "EQE 350+",
    trim: "AMG Line",
    generation: "V295",
    generationCode: "V295",
    yearFrom: null,
    yearTo: null,
    fuelType: "ELECTRIC",
    confidence: "REJECTED",
    verifiedForTurkey: false,
    category: "Otomobil",
    notes:
      "REJECTED: Official TR EQE satırları EQE 280 ve EQE 350 4MATIC — 'EQE 350+' TR listesinde yok.",
    sources: [S.officialEqe, S.webteknoAug],
  }),
  row({
    series: "GLB",
    model: "GLB 200",
    trim: "AMG Line",
    generation: "X247 new",
    generationCode: "X247",
    yearFrom: null,
    yearTo: null,
    fuelType: "GASOLINE",
    confidence: "REJECTED",
    verifiedForTurkey: false,
    category: "Arazi, SUV & Pickup",
    notes:
      "REJECTED for current new-gen MY: Aug 2026 TR yeni GLB satırları GLB 200+ (elektrik) ve GLB 220 4MATIC — benzinli 'GLB 200' bu nesilde listelenmedi (eski Progressive/AMG arşivi ayrı).",
    sources: [S.webteknoAug, S.dhAug],
  }),
  row({
    series: "C Serisi",
    model: "C 200 4MATIC",
    trim: "AMG",
    generation: "W206",
    generationCode: "W206",
    yearFrom: null,
    yearTo: null,
    confidence: "REJECTED",
    verifiedForTurkey: false,
    category: "Otomobil",
    notes:
      "REJECTED trim label: resmi satır 'AMG' yazsa da katalog trim alanı 'AMG Line' olmalı; 'AMG' tek başına Mercedes-AMG modeliyle karışır.",
    sources: [S.officialC, S.mbHome],
  }),
];

const verified = configurations.filter(
  (c) => c.confidence === "VERIFIED_OFFICIAL" || c.confidence === "VERIFIED_MULTI_SOURCE"
);
const reviewRequired = configurations.filter((c) => c.confidence === "REVIEW_REQUIRED");
const rejected = configurations.filter((c) => c.confidence === "REJECTED");
const seriesCovered = [...new Set(configurations.map((c) => c.series))];

const doc = {
  brand: "Mercedes-Benz",
  brandSlug: "mercedes-benz",
  version: "2026.08-deep-mercedes-v3-official-plus-archives",
  generatedAt: new Date().toISOString(),
  seriesCovered,
  status: "IN_PROGRESS",
  notes:
    "TR official fiyat.mercedes-benz.com.tr MY2026 + Aug 2026 published tables + May/Oct 2024 and Jan 2021 archives. Package 'AMG' normalized to AMG Line. Mercedes-AMG performance models kept as distinct versions. EQB/EQE SUV/EQS SUV/CLS/SLC/SLK/Vito/V-Class remain REVIEW; invented wrong versions REJECTED.",
  configurations,
  researchNotes: {
    researchedSeriesPass: seriesCovered,
    historicalArchivesIngested: [
      "2021-01 C Serisi W205",
      "2024-05 MB TR (Onedio)",
      "2024-10 MB TR (Otomobilir)",
      "2026-08 WebTekno + DonanımHaber",
    ],
    reviewRequiredSeries: reviewRequired.map((c) => c.series),
    rejectedNotes: rejected.map((c) => `${c.series} ${c.model} ${c.trim}`.trim()),
  },
};

writeFileSync(OUT, JSON.stringify(doc, null, 2));
console.log(
  JSON.stringify(
    {
      ok: true,
      total: configurations.length,
      verified: verified.length,
      verifiedOfficial: configurations.filter((c) => c.confidence === "VERIFIED_OFFICIAL").length,
      verifiedMulti: configurations.filter((c) => c.confidence === "VERIFIED_MULTI_SOURCE")
        .length,
      reviewRequired: reviewRequired.length,
      rejected: rejected.length,
      series: seriesCovered.length,
      seriesCovered,
    },
    null,
    2
  )
);
