/** Sistem ayarı meta + profesyonel UI kontrol tipleri */
export type SettingControl =
  | "toggle"
  | "number"
  | "text"
  | "textarea"
  | "select"
  | "color"
  | "numberList"
  | "bidTokenCosts"
  | "categoryCosts"
  | "accountFees"
  | "stringList"
  | "flagMap"
  | "categoryAccessRules"
  | "businessTypes"
  | "json";

export type SettingOption = { value: string; label: string };

export type SettingMeta = {
  value: unknown;
  label: string;
  group: string;
  description?: string;
  control?: SettingControl;
  options?: SettingOption[];
  min?: number;
  max?: number;
  unit?: string;
};

export const SETTING_GROUP_LABELS: Record<string, string> = {
  bid: "Teklif Kuralları",
  token: "Jeton",
  listing: "İlan",
  lifecycle: "Yaşam Döngüsü",
  auth: "Kimlik Doğrulama",
  commercial: "Ticari Üyelik",
  notification: "Bildirimler",
  pwa: "PWA",
  general: "Genel",
  v2: "v2 Tema Ayarları",
  ads: "Reklam Ayarları",
  eids: "EİDS",
  payment: "Ödeme / Sanal POS",
  ai: "AI (Yapay Zeka)",
  account: "Kullanıcı / Hesap",
  escrow: "Güvenli Öde (Escrow)",
};

const CAT_COST_KEYS = [
  { key: "konut", label: "Konut / Emlak" },
  { key: "arac", label: "Vasıta" },
  { key: "isyeri", label: "İşyeri" },
  { key: "arsa", label: "Arsa" },
  { key: "kiralik", label: "Kiralık" },
  { key: "ikinci-el", label: "İkinci El" },
  { key: "sifir-urun", label: "Sıfır Ürün" },
];

export const CATEGORY_COST_OPTIONS = CAT_COST_KEYS;

export const DEFAULT_SETTINGS: Record<string, SettingMeta> = {
  bid_step_tl: {
    value: 10000,
    label: "Teklif basamağı",
    group: "bid",
    description: "Her yeni teklif en az bu tutar kadar artmalıdır (TL).",
    control: "number",
    min: 1,
    unit: "TL",
  },
  bid_step_by_category: {
    value: {},
    label: "Kategoriye özel teklif basamağı",
    group: "bid",
    description: "Boş bırakılan kategorilerde genel basamak kullanılır.",
    control: "categoryCosts",
    unit: "TL",
  },
  require_higher_than_highest: {
    value: true,
    label: "En yüksek tekliften yüksek olmalı",
    group: "bid",
    description: "Açıksa yeni teklif, mevcut en yüksek tekliften fazla olmalıdır.",
    control: "toggle",
  },
  max_bids_per_user_per_listing: {
    value: 4,
    label: "Kullanıcı başına max teklif (ilan)",
    group: "bid",
    description: "Aynı kullanıcı aynı ilana en fazla kaç teklif verebilir.",
    control: "number",
    min: 1,
    max: 20,
  },
  second_bid_replaces_previous: {
    value: true,
    label: "Yeni teklif eskisinin yerine geçer",
    group: "bid",
    control: "toggle",
  },
  second_bid_must_be_higher: {
    value: true,
    label: "2. teklif birinciden yüksek olmalı",
    group: "bid",
    control: "toggle",
  },
  bid_duration_options_days: {
    value: [1, 3, 7],
    label: "Teklif süresi seçenekleri",
    group: "bid",
    description: "Kullanıcıya sunulacak teklif geçerlilik süreleri (gün).",
    control: "numberList",
    unit: "gün",
  },
  bid_can_exceed_listing_end: {
    value: false,
    label: "Teklif süresi ilan bitişini aşabilir",
    group: "bid",
    control: "toggle",
  },
  bid_exceed_policy: {
    value: "clamp",
    label: "İlan bitişini aşma politikası",
    group: "bid",
    description: "Teklif süresi ilan bitişini geçtiğinde uygulanacak kural.",
    control: "select",
    options: [
      { value: "allow", label: "İzin ver (aşmasına izin ver)" },
      { value: "clamp", label: "Kısalt (ilan bitişine sabitle)" },
      { value: "block", label: "Engelle (kabul etme)" },
    ],
  },
  token_refund_on_withdraw: {
    value: false,
    label: "Teklif geri çekmede jeton iadesi",
    group: "bid",
    control: "toggle",
  },

  token_cost_base: {
    value: 1,
    label: "Temel jeton maliyeti / teklif",
    group: "token",
    control: "number",
    min: 0,
    unit: "jeton",
  },
  token_cost_by_category: {
    value: {},
    label: "Kategoriye göre jeton maliyeti",
    group: "token",
    description: "Boş = temel maliyet kullanılır.",
    control: "categoryCosts",
    unit: "jeton",
  },
  token_cost_by_bid_number: {
    value: { "1": 1, "2": 1 },
    label: "Kaçıncı teklife göre jeton",
    group: "token",
    description: "1. teklif, 2. teklif… için harcanacak jeton.",
    control: "bidTokenCosts",
  },
  quick_token_enabled: {
    value: true,
    label: "Hızlı jeton al (aç / kapat)",
    group: "token",
    description: "Kapalıysa kullanıcılar yalnızca paketlerden jeton alabilir.",
    control: "toggle",
  },
  quick_token_presets: {
    value: [1, 5, 10, 25, 50, 100],
    label: "Hızlı jeton miktarları",
    group: "token",
    description: "Hızlı al butonlarında görünen jeton adetleri.",
    control: "numberList",
    unit: "jeton",
  },
  quick_token_max: {
    value: 10000,
    label: "Hızlı jeton üst limiti",
    group: "token",
    description: "Özel miktar ile tek seferde alınabilecek en fazla jeton.",
    control: "number",
    min: 1,
    max: 100000,
    unit: "jeton",
  },
  quick_token_price_per_token_tl: {
    value: 0,
    label: "Hızlı jeton birim fiyatı",
    group: "token",
    description: "0 = ücretsiz/demo. 0’dan büyükse arayüzde TL karşılığı gösterilir.",
    control: "number",
    min: 0,
    unit: "TL / jeton",
  },
  vehicle_nav_show_empty_brands: {
    value: false,
    label: "Vasıta: ilanı olmayan markaları göster",
    group: "listing",
    description: "Kapalıysa sol menüde yalnızca ilanı olan markalar görünür.",
    control: "toggle",
  },
  vehicle_nav_show_empty_models: {
    value: false,
    label: "Vasıta: ilanı olmayan modelleri göster",
    group: "listing",
    description: "Kapalıysa yalnızca ilanı olan modeller görünür.",
    control: "toggle",
  },
  vehicle_nav_show_empty_trims: {
    value: false,
    label: "Vasıta: ilanı olmayan motor/paket seçeneklerini göster",
    group: "listing",
    description: "Varsayılan kapalı — motor/paket (ör. 320d) yalnızca ilanı varsa listelenir.",
    control: "toggle",
  },
  category_nav_show_empty: {
    value: false,
    label: "İlanı olmayan alt kategorileri göster",
    group: "listing",
    description:
      "Kapalıysa sol kategori ağacında (Emlak/Vasıta/alışveriş) ilanı 0 olan dallar gizlenir. Marka/model için üstteki Vasıta ayarları geçerlidir.",
    control: "toggle",
  },
  browse_nav_config: {
    value: {
      hideEmptyUntilListing: true,
      sahibindenTreeExpand: true,
      nodes: {} as Record<string, { active?: boolean; sortOrder?: number }>,
    },
    label: "Kategori menü görünürlüğü",
    group: "listing",
    description:
      "İlanı olmayan dalların gizlenmesi, Sahibinden menü ağaç açılımı ve vasıta/emlak/premium düğüm ayarları. Admin Kategoriler paneli yönetir.",
    control: "json",
  },

  listing_min_days: {
    value: 3,
    label: "İlan minimum süresi",
    group: "listing",
    control: "number",
    min: 1,
    unit: "gün",
  },
  listing_max_days: {
    value: 30,
    label: "İlan maksimum süresi",
    group: "listing",
    control: "number",
    min: 1,
    unit: "gün",
  },
  listing_fee_mode: {
    value: "free",
    label: "İlan ücreti modu",
    group: "listing",
    description:
      "Ücretsiz: herkes bedava. Ücretli: her ilan ücretli. Freemium: önce ücretsiz kota, sonra ücret.",
    control: "select",
    options: [
      { value: "free", label: "Ücretsiz" },
      { value: "paid", label: "Ücretli" },
      { value: "freemium", label: "Freemium (kota + ücret)" },
    ],
  },
  listing_free_quota: {
    value: 3,
    label: "Ücretsiz ilan kotası (freemium)",
    group: "listing",
    description: "Freemium modunda kullanıcı başına kaç ilan ücretsiz. Örn: 1 → yalnızca ilk ilan bedava.",
    control: "number",
    min: 0,
  },
  listing_fee_tl: {
    value: 0,
    label: "İlan ücreti (genel)",
    group: "listing",
    description: "Üyelik tipine özel fiyat 0 ise bu genel tutar kullanılır.",
    control: "number",
    min: 0,
    unit: "TL",
  },
  listing_fee_by_account_type: {
    value: { BIREYSEL_TICARI: 0, TICARI: 0, BIREYSEL: 0, EMLAKCI: 0, GALERICI: 0 },
    label: "Üyelik tipine göre ilan ücreti",
    group: "listing",
    description:
      "Bireysel / Emlakçı / Galerici için ayrı fiyat. 0 yazarsanız yukarıdaki genel ilan ücreti geçerli olur.",
    control: "accountFees",
    unit: "TL",
  },
  premium_title_bold_tl: {
    value: 49,
    label: "Premium: Kalın başlık ücreti",
    group: "listing",
    description: "İlan başlığını kalın (bold) gösterir.",
    control: "number",
    min: 0,
    unit: "TL",
  },
  premium_title_large_tl: {
    value: 49,
    label: "Premium: Büyük harf başlık ücreti",
    group: "listing",
    description: "İlan başlığını otomatik BÜYÜK HARF ile gösterir.",
    control: "number",
    min: 0,
    unit: "TL",
  },
  premium_colored_tl: {
    value: 79,
    label: "Premium: Renkli ilan ücreti",
    group: "listing",
    description: "Kart kenarlığı / vurgu rengi (turuncu çerçeve).",
    control: "number",
    min: 0,
    unit: "TL",
  },
  premium_feature_3d_tl: {
    value: 149,
    label: "Premium: 3 gün ana sayfa",
    group: "listing",
    description: "Onay sonrası 3 gün ana sayfada Premium / öne çıkan olarak kalır.",
    control: "number",
    min: 0,
    unit: "TL",
  },
  premium_feature_7d_tl: {
    value: 249,
    label: "Premium: 7 gün ana sayfa",
    group: "listing",
    description: "Onay sonrası 7 gün (1 hafta) ana sayfada Premium / öne çıkan olarak kalır.",
    control: "number",
    min: 0,
    unit: "TL",
  },
  listing_fee_vat_percent: {
    value: 20,
    label: "İlan ücreti KDV oranı",
    group: "listing",
    description: "İlan / premium özellik ödemelerinde KDV yüzdesi (0 = KDV gösterme).",
    control: "number",
    min: 0,
    max: 40,
    unit: "%",
  },
  listing_fee_prices_include_vat: {
    value: true,
    label: "Fiyatlara KDV dahil",
    group: "listing",
    description:
      "Açıkken admin’in girdiği TL tutarlar KDV dahildir. Kapalıysa tutarlar KDV hariçtir; ödeme anında KDV eklenir.",
    control: "toggle",
  },
  premium_badge_rule: {
    value: "premium_3",
    label: "Premium logosu ne zaman görünsün?",
    group: "listing",
    description:
      "Karttaki yeşil Premium rozetinin görünme kuralı. Örn. en az 3 premium özellik alan ilanlarda göster.",
    control: "select",
    options: [
      { value: "never", label: "Hiç gösterme" },
      { value: "paid", label: "Paralı açılan ilan (ücret ödenmiş)" },
      { value: "store", label: "Mağaza ilanı (emlakçı / galerici / shop)" },
      { value: "featured", label: "Ana sayfa öne çıkarma (3/7 gün) aktifse" },
      { value: "premium_2", label: "En az 2 premium özellik alınmışsa" },
      { value: "premium_3", label: "En az 3 premium özellik alınmışsa" },
      { value: "premium_4", label: "4 premium özelliğin hepsi alınmışsa" },
    ],
  },
  listing_edit_while_live: {
    value: true,
    label: "Yayındaki ilan düzenlenebilir",
    group: "listing",
    description: "Kapalıysa satıcı önce ilanı kaldırmalıdır.",
    control: "toggle",
  },
  listing_auto_approve: {
    value: false,
    label: "İlanları otomatik onayla",
    description: "Açıksa yeni ilanlar onay kuyruğuna düşmeden yayına alınır.",
    group: "listing",
    control: "toggle",
  },
  housing_form_fields_enabled: {
    value: {
      kitchen: true,
      usageStatus: true,
      inSite: true,
      siteName: true,
      elevator: true,
      creditEligible: true,
      energyCertificate: true,
      sellerType: true,
      swap: true,
    },
    label: "Konut ek özellikleri (form)",
    group: "listing",
    description:
      "İlan ver formunda görünecek opsiyonel konut alanları. Kapalı alan forma gelmez; açık olup seçilmeyenler önizlemede “Belirtilmedi” olur.",
    control: "flagMap",
    options: [
      { value: "kitchen", label: "Mutfak" },
      { value: "usageStatus", label: "Kullanım durumu" },
      { value: "inSite", label: "Site içinde mi" },
      { value: "siteName", label: "Site adı" },
      { value: "elevator", label: "Asansör" },
      { value: "creditEligible", label: "Krediye uygun" },
      { value: "energyCertificate", label: "Enerji kimlik belgesi" },
      { value: "sellerType", label: "Satıcı (Sahibi / Emlak Ofisi)" },
      { value: "swap", label: "Takas" },
    ],
  },

  post_end_selection_minutes: {
    value: 30,
    label: "Bitiş sonrası seçim penceresi (eski)",
    group: "lifecycle",
    description:
      "Geriye dönük uyumluluk. Asıl kural aşağıdaki «Süre dolunca» formundaki teklifli seçim dakikasıdır; kayıtta senkronlanır.",
    control: "number",
    min: 0,
    unit: "dakika",
  },
  listing_expiry_rules: {
    value: {
      bidding: {
        afterEnd: "selection",
        selectionMinutes: 30,
        graceMinutes: 0,
        expiredVisibleDays: 7,
        onApprove: "show_completed",
        approvedVisibleDays: 14,
      },
      classified: {
        afterEnd: "grace",
        graceDays: 3,
        expiredVisibleDays: 7,
      },
      buy: {
        afterEnd: "hide_immediate",
        graceDays: 0,
        expiredVisibleDays: 3,
        closesWhenBiddingEnds: true,
      },
      buyButtonLabel: "Satın al",
    },
    label: "Süre dolunca (teklifli / teklifsiz / satın al)",
    group: "lifecycle",
    description:
      "Teklifli, teklifsiz ve Satın al (Al butonu / Güvenli Öde) ilanlarında süre bitince vitrin davranışı. Hibritte teklif süresi bitince Al kapanır.",
    control: "expiryRules",
  },
  republish_wait_hours: {
    value: 24,
    label: "Yeniden yayın bekleme",
    group: "lifecycle",
    control: "number",
    min: 0,
    unit: "saat",
  },
  republish_mode: {
    value: "same_reset",
    label: "Yeniden yayın modu",
    group: "lifecycle",
    control: "select",
    options: [
      { value: "same_reset", label: "Aynı ilanı sıfırla" },
      { value: "new_copy", label: "Yeni kopya oluştur" },
    ],
  },
  on_approve_reject_others: {
    value: true,
    label: "Onayda diğer teklifleri reddet",
    group: "lifecycle",
    control: "toggle",
  },
  approval_mode: {
    value: "meeting",
    label: "Onay modu",
    group: "lifecycle",
    control: "select",
    options: [
      { value: "meeting", label: "Görüşme / buluşma" },
      { value: "sale", label: "Satış onayı" },
    ],
  },
  contact_reveal: {
    value: { phone: true, in_app_message: true, name: true },
    label: "Onay sonrası açılacak iletişim (genel)",
    group: "lifecycle",
    description:
      "Kategori kuralı «teklif onayından sonra» iken hangi alanların açılacağını belirler. Kategoriye özel zamanlama aşağıdaki tablodan seçilir.",
    control: "flagMap",
    options: [
      { value: "phone", label: "Telefon" },
      { value: "in_app_message", label: "Uygulama içi mesaj" },
      { value: "name", label: "Ad soyad" },
    ],
  },
  messaging_access: {
    value: "approved",
    label: "Mesajlaşma varsayılanı (kategori yoksa)",
    group: "lifecycle",
    description:
      "Kategori kuralı tanımlı değilse kullanılır. «Sahibinden Teklifsiz» ürün modunda otomatik olarak giriş yapan herkese açılır (bu ayar ezilir; teklifli moda dönünce eski kural geri gelir).",
    control: "select",
    options: [
      { value: "approved", label: "Yalnızca teklifi onaylananlar" },
      { value: "everyone", label: "Herkes (giriş yapan)" },
    ],
  },
  seller_visibility_by_category: {
    value: {
      konut: { identity: "approved", contact: "approved", messaging: "approved" },
      arac: { identity: "approved", contact: "approved", messaging: "approved" },
      isyeri: { identity: "approved", contact: "approved", messaging: "approved" },
      arsa: { identity: "approved", contact: "approved", messaging: "approved" },
      kiralik: { identity: "approved", contact: "approved", messaging: "approved" },
      "ikinci-el": { identity: "logged_in", contact: "logged_in", messaging: "logged_in" },
      "sifir-urun": { identity: "logged_in", contact: "logged_in", messaging: "logged_in" },
      "premium-otel": { identity: "approved", contact: "approved", messaging: "approved" },
      "premium-lojistik": { identity: "approved", contact: "approved", messaging: "approved" },
      "premium-yolculuk": { identity: "approved", contact: "approved", messaging: "approved" },
    },
    label: "Üst kategori — kimlik / iletişim / mesaj",
    group: "lifecycle",
    description:
      "Her üst kategoride ilan sahibi kimliği, telefon ve mesajlaşmanın ne zaman açılacağını seçin. Örn. Vasıta: onay sonrası; İkinci El (teknoloji): giriş yapan herkese onaysız.",
    control: "categoryAccessRules",
  },

  otp_provider: {
    value: "dev",
    label: "OTP sağlayıcı",
    group: "auth",
    control: "select",
    options: [
      { value: "dev", label: "Geliştirme (sabit kod)" },
      { value: "sms", label: "SMS" },
    ],
  },
  otp_dev_code: {
    value: "1234",
    label: "Geliştirme OTP kodu",
    group: "auth",
    control: "text",
  },
  phone_verification_required: {
    value: true,
    label: "Telefon doğrulama zorunlu",
    group: "auth",
    control: "toggle",
  },

  commercial_business_types: {
    value: [
      { key: "EMLAK_OFISI", label: "Emlak Ofisi", active: true, sortOrder: 0 },
      { key: "GALERI", label: "Galeri", active: true, sortOrder: 1 },
      { key: "MAGAZA", label: "Mağaza", active: true, sortOrder: 2 },
      { key: "OTEL", label: "Otel", active: true, sortOrder: 3 },
      { key: "LOJISTIK", label: "Lojistik", active: true, sortOrder: 4 },
    ],
    label: "Kurumsal işletme tipleri",
    group: "commercial",
    description:
      "Üye olurken seçilen faaliyet alanları (Emlak Ofisi, Galeri vb.). Yeni tip eklenince kayıt formu ve Kullanıcılar → Kurumsal sekmelerine yansır. Anahtar (key) sonradan değiştirilmez.",
    control: "businessTypes",
  },
  commercial_register_demo_fill_enabled: {
    value: true,
    label: "Ticari kayıt — Demo doldur tuşu",
    group: "commercial",
    description:
      "Üye ol formunda Ticari seçildiğinde «Demo doldur» ile rastgele işletme bilgisi basılır. Kapalıysa tuş gizlenir.",
    control: "toggle",
  },
  commercial_approval_required: {
    value: true,
    label: "Ticari üyelik yönetici onayı zorunlu",
    group: "commercial",
    description: "Açıkken yeni Ticari hesaplar PENDING kalır; yönetici onaylayınca aktif olur.",
    control: "toggle",
  },
  shop_package_buy_popup_bireysel: {
    value: true,
    label: "İlan paketi satın alma (Bireysel)",
    group: "commercial",
    description:
      "Açıkken bireysel üyeler Hesabım’dan paket alabilir; limit dolunca satın alma popup’ı çıkar. Kapalıysa bireysel için paket satışı gizlenir. Admin ataması her zaman çalışır.",
    control: "toggle",
  },
  shop_package_buy_popup_ticari: {
    value: true,
    label: "İlan paketi satın alma (Ticari)",
    group: "commercial",
    description:
      "Açıkken ticari (kurumsal) üyeler paket yoksa / limit dolunca satın alma popup’ı görür. Kapalıysa yalnızca uyarı metni gösterilir. Admin ataması her zaman çalışır.",
    control: "toggle",
  },
  shop_package_pay_with_tokens_enabled: {
    value: false,
    label: "Kurumsal paket — jeton ile ödeme (eski)",
    group: "commercial",
    description:
      "Paket ödeme tipi artık Demo POS’a bağlıdır: POS kapalı → yalnızca jeton; POS açık → TL. Bu anahtar kullanılmaz.",
    control: "toggle",
  },
  premium_pay_with_tokens_enabled: {
    value: false,
    label: "Premium ilan — jeton ile ödeme",
    group: "listing",
    description:
      "Açıkken premium özellikler (kalın başlık, renkli, öne çıkarma vb.) jetonla da ödenebilir. Aşağıdaki jeton fiyatları kullanılır.",
    control: "toggle",
  },
  premium_title_bold_tokens: {
    value: 5,
    label: "Premium jeton: Kalın başlık",
    group: "listing",
    description: "Jeton ile ödemede kalın başlık ücreti.",
    control: "number",
    min: 0,
    unit: "jeton",
  },
  premium_title_large_tokens: {
    value: 5,
    label: "Premium jeton: Büyük harf başlık",
    group: "listing",
    description: "Jeton ile ödemede büyük harf başlık ücreti.",
    control: "number",
    min: 0,
    unit: "jeton",
  },
  premium_colored_tokens: {
    value: 8,
    label: "Premium jeton: Renkli ilan",
    group: "listing",
    description: "Jeton ile ödemede renkli ilan ücreti.",
    control: "number",
    min: 0,
    unit: "jeton",
  },
  premium_feature_3d_tokens: {
    value: 15,
    label: "Premium jeton: 3 gün ana sayfa",
    group: "listing",
    description: "Jeton ile ödemede 3 gün öne çıkarma ücreti.",
    control: "number",
    min: 0,
    unit: "jeton",
  },
  premium_feature_7d_tokens: {
    value: 25,
    label: "Premium jeton: 7 gün ana sayfa",
    group: "listing",
    description: "Jeton ile ödemede 7 gün öne çıkarma ücreti.",
    control: "number",
    min: 0,
    unit: "jeton",
  },
  account_payments_visible_bireysel: {
    value: true,
    label: "Özet: Faturalar/Ödemeler (Bireysel)",
    group: "commercial",
    description: "Bireysel üye hesabım özetinde Faturalar / Ödemeler tablosunu göster.",
    control: "toggle",
  },
  account_payments_visible_ticari: {
    value: true,
    label: "Özet: Faturalar/Ödemeler (Ticari)",
    group: "commercial",
    description: "Ticari üye hesabım özetinde Faturalar / Ödemeler tablosunu göster.",
    control: "toggle",
  },
  commercial_notify_demo_mode: {
    value: true,
    label: "Ticari onay bildirimleri — Demo mod",
    group: "commercial",
    description:
      "Açıkken onay mail/SMS gerçek gönderilmez, yalnızca loglanır. Kapatınca gerçek e-posta/SMS altyapısı kullanılır.",
    control: "toggle",
  },
  commercial_approval_notify_email: {
    value: true,
    label: "Onayda e-posta gönder",
    group: "commercial",
    description: "Ticari üye onay/red sonrası e-posta (demo modda simüle edilir).",
    control: "toggle",
  },
  commercial_approval_notify_sms: {
    value: true,
    label: "Onayda SMS gönder",
    group: "commercial",
    description: "Ticari üye onay/red sonrası SMS (demo modda simüle edilir).",
    control: "toggle",
  },
  commercial_premium_badge_enabled: {
    value: true,
    label: "Premium üye rozeti (görünüm)",
    group: "commercial",
    description: "Açıkken admin’in premium işaretlediği ticari üyelerde «Premium Üye» rozeti gösterilir.",
    control: "toggle",
  },
  commercial_member_years_badge_enabled: {
    value: true,
    label: "Üyelik yılı rozeti",
    group: "commercial",
    description: "Ticari ilan sahibi kartında «X yıldır üye» rozetini göster.",
    control: "toggle",
  },
  commercial_logo_enabled: {
    value: true,
    label: "Ticari logo yükleme",
    group: "commercial",
    description: "Ticari üyelerin işletme logosu yüklemesine izin ver.",
    control: "toggle",
  },
  commercial_logo_paid: {
    value: false,
    label: "Logo yükleme ücretli",
    group: "commercial",
    description: "Açıkken logo yüklemek için jeton kesilir. Kapalıysa ücretsiz.",
    control: "toggle",
  },
  commercial_logo_fee_tokens: {
    value: 10,
    label: "Logo jeton ücreti",
    group: "commercial",
    description: "Logo ücretliyse kesilecek jeton.",
    control: "number",
    min: 0,
    max: 9999,
    unit: "jeton",
  },
  seller_reviews_enabled: {
    value: false,
    label: "Satıcı yorumları",
    group: "commercial",
    description:
      "Kapalıyken ilan detayında Yorumlar sekmesi «Çok yakında» gösterir. Açılınca yorumlar aktif olur.",
    control: "toggle",
  },
  seller_reviews_auto_approve: {
    value: false,
    label: "Yorumlar otomatik onay",
    group: "commercial",
    description:
      "Açıkken yorumlar anında yayınlanır. Kapalıysa her yorum yönetici onayına düşer.",
    control: "toggle",
  },
  seller_reviews_min_length: {
    value: 20,
    label: "Yorum min. karakter",
    group: "commercial",
    control: "number",
    min: 10,
    max: 500,
  },

  notification_channels: {
    value: { IN_APP: true, EMAIL: false, SMS: false, PUSH: false },
    label: "Bildirim kanalları",
    group: "notification",
    control: "flagMap",
    options: [
      { value: "IN_APP", label: "Uygulama içi" },
      { value: "EMAIL", label: "E-posta" },
      { value: "SMS", label: "SMS" },
      { value: "PUSH", label: "Push" },
    ],
  },
  notification_events: {
    value: {
      bid_received: true,
      bid_approved: true,
      bid_rejected: true,
      listing_approved: true,
      listing_rejected: true,
      listing_extension_approved: true,
      listing_extension_rejected: true,
      listing_edit_approved: true,
      listing_edit_rejected: true,
      favorite_listing_edited: true,
      favorite_price_dropped: true,
      favorite_price_rose: true,
      favorite_bid_over_ask: true,
      favorite_new_high_bid: true,
      listing_ending_soon: true,
      listing_ended: true,
      token_low: true,
      message_received: true,
      shop_package_assigned: true,
      shop_package_changed: true,
      shop_package_cancelled: true,
    },
    label: "Bildirim olayları",
    group: "notification",
    control: "flagMap",
    options: [
      { value: "bid_received", label: "Teklif alındı" },
      { value: "bid_approved", label: "Teklif onaylandı" },
      { value: "bid_rejected", label: "Teklif reddedildi" },
      { value: "listing_approved", label: "İlan onaylandı" },
      { value: "listing_rejected", label: "İlan reddedildi" },
      { value: "listing_extension_approved", label: "Süre uzatma onay" },
      { value: "listing_extension_rejected", label: "Süre uzatma red" },
      { value: "listing_edit_approved", label: "Düzenleme onay" },
      { value: "listing_edit_rejected", label: "Düzenleme red" },
      { value: "favorite_listing_edited", label: "Favori ilan düzenlendi" },
      { value: "favorite_price_dropped", label: "Favori fiyat düştü" },
      { value: "favorite_price_rose", label: "Favori fiyat arttı" },
      { value: "favorite_bid_over_ask", label: "Favoride talep üstü teklif" },
      { value: "favorite_new_high_bid", label: "Favoride yeni yüksek teklif" },
      { value: "listing_ending_soon", label: "İlan bitmek üzere" },
      { value: "listing_ended", label: "İlan bitti" },
      { value: "token_low", label: "Jeton düşük" },
      { value: "message_received", label: "Mesaj alındı" },
      { value: "shop_package_assigned", label: "Kurumsal paket atandı" },
      { value: "shop_package_changed", label: "Kurumsal paket değişti" },
      { value: "shop_package_cancelled", label: "Kurumsal paket iptal" },
    ],
  },

  pwa_enabled: { value: true, label: "PWA aktif", group: "pwa", control: "toggle" },
  pwa_force_on_mobile: {
    value: false,
    label: "Mobilde PWA’ya yönlendir",
    group: "pwa",
    control: "toggle",
  },
  brand_name: { value: "TeklifBu", label: "Marka adı", group: "general", control: "text" },
  site_footer: {
    value: {
      phoneLabel: "Müşteri Hizmetleri",
      phone: "0216 606 60 00",
      address:
        "Adres: Atatürk Mah. Ertuğrul Gazi Sk. Metropol İstanbul Sitesi C1 Blok No: 2b İç Kapı No: 303 Ataşehir / İSTANBUL",
      tradeRegistryNo: "1073204",
      mersis: "0752106837400001",
      disclaimer:
        "teklifbu.com'da yer alan kullanıcıların oluşturduğu tüm içerik, görüş ve bilgilerin doğruluğunu garanti etmez. İçeriklerin sorumluluğu içerik sağlayıcılarına aittir. Yer sağlanan içerikler hakkında her türlü fikri ve sınai mülkiyet hakları ihlali, haksız rekabet, kişilik hakları ihlali gibi durumlarda 5651 sayılı Kanun kapsamında bildirimlerinizi iletişime geçerek iletebilirsiniz. Yapılan bildirimlerin incelenmesi sonucunda gerekli görülen aksiyonlar alınacaktır.",
      googlePlayUrl: "#",
      appStoreUrl: "#",
      appGalleryUrl: "#",
      etbisText: "ETBİS'e Kayıtlıdır.",
      etbisQrUrl: "",
      version: "v1.0.0",
      showPaymentIcons: true,
      showAppBadges: true,
      showEtbis: true,
    },
    label: "Site alt bilgi (footer)",
    group: "general",
    description: "Ana sayfa altındaki müşteri hizmetleri, adres, MERSİS, yasal metin ve uygulama linkleri. Admin → Footer menüsünden düzenlenir.",
    control: "json",
  },
  brand_primary: {
    value: "#FF6A00",
    label: "Ana renk (turuncu)",
    group: "general",
    control: "color",
  },
  brand_navy: { value: "#0B1F3A", label: "Navy renk", group: "general", control: "color" },
  marketplace_mode: {
    value: "bidding",
    label: "Ürün modu (Teklif / Sahibinden)",
    group: "v2",
    description:
      "TeklifBu: teklif butonu, teklif akışı, teklif istatistikleri açık. Sahibinden Teklifsiz: teklif UX kapanır; iletişim/mesaj açılır; ana sayfa ilan odaklı olur. Kod silinmez — geri alınca teklifli sistem döner.",
    control: "select",
    options: [
      { value: "bidding", label: "TeklifBu — teklifli sistem" },
      { value: "classified", label: "Sahibinden Teklifsiz — ilan platformu" },
    ],
  },
  ui_theme: {
    value: "v1",
    label: "Site teması",
    group: "v2",
    description: "v1: mevcut arayüz. v2: pazar yeri düzeni. Ürün modundan bağımsızdır.",
    control: "select",
    options: [
      { value: "v1", label: "v1 — Klasik" },
      { value: "v2", label: "v2 — Pazar yeri" },
    ],
  },
  ui_categories_theme: {
    value: "v2",
    label: "Kategoriler teması",
    group: "v2",
    description:
      "Site teması v2 iken. v2: ilk mockup. Ağaç: Emlak/Vasıta alt alta.",
    control: "select",
    options: [
      { value: "v2", label: "v2 — İlk tema (mockup)" },
      { value: "tree", label: "Ağaç — İlanlar gibi (alt alta)" },
    ],
  },
  v2_home_grid_cols: {
    value: "4",
    label: "Ana sayfa satırdaki ilan",
    group: "v2",
    description:
      "4 / 5 / 6. Sayfa genişliği ve kart boyutu buna göre ayarlanır. Sistemi yormaz — sadece CSS.",
    control: "select",
    options: [
      { value: "4", label: "4 ilan (daha geniş kart, dar sayfa)" },
      { value: "5", label: "5 ilan" },
      { value: "6", label: "6 ilan (daha küçük kart, geniş sayfa)" },
    ],
  },
  home_listings_rows: {
    value: "3",
    label: "Ana sayfa vitrin satır sayısı",
    group: "v2",
    description:
      "Ana sayfada sayfa başına kaç satır ilan. Sayfa boyutu = satır × kolon (4/5/6). Örn. 3×4 = 12 ilan/sayfa. Vitrinde daha fazla ilan varsa önceki/sonraki ve sayfa numaraları ile gezinilir.",
    control: "select",
    options: [
      { value: "3", label: "3 satır (4’lüde 12 · 5’lide 15 · 6’lıda 18)" },
      { value: "4", label: "4 satır (4’lüde 16 · 5’lide 20 · 6’lıda 24)" },
      { value: "5", label: "5 satır (4’lüde 20 · 5’lide 25 · 6’lıda 30)" },
      { value: "6", label: "6 satır (4’lüde 24 · 5’lide 30 · 6’lıda 36)" },
      { value: "7", label: "7 satır (4’lüde 28 · 5’lide 35 · 6’lıda 42)" },
      { value: "8", label: "8 satır (4’lüde 32 · 5’lide 40 · 6’lıda 48)" },
    ],
  },
  featured_card_title_price_only: {
    value: false,
    label: "Öne çıkanlarda sadece başlık + fiyat",
    group: "v2",
    description:
      "Açıkken «Öne çıkan ilanlar» kartlarında konum, piyasa fiyatı, teklif sayısı vb. gizlenir; yalnızca başlık ve ilan fiyatı yazılır. Kapalıyken mevcut görünüm korunur. Tüm temalarda (v1 / v2) geçerlidir.",
    control: "toggle",
  },
  featured_card_hover_lift: {
    value: true,
    label: "Öne çıkanlarda hover’da yükselt",
    group: "v2",
    description:
      "Açıkken fare öne çıkan vitrin ilanının üzerine gelince kart hafifçe öne çıkar (yükselme + gölge). Kapalıysa hover efekti uygulanmaz. Tüm temalarda geçerlidir.",
    control: "toggle",
  },
  v2_header_belt: {
    value: "navy",
    label: "Üst kuşak rengi",
    group: "v2",
    description:
      "Üst header (kuşak) zemini. Lacivert: açık yazı / beyaz logo. Beyaz: koyu yazı / siyah logo (B turuncu kalır).",
    control: "select",
    options: [
      { value: "navy", label: "Lacivert (koyu)" },
      { value: "white", label: "Beyaz (açık)" },
    ],
  },
  v2_footer_belt: {
    value: "white",
    label: "Alt kuşak rengi",
    group: "v2",
    description:
      "Site footer (alt kuşak) zemini. Üst kuşakla aynı rengi seçebilirsiniz. Lacivertte yazı/logo açık renk olur; beyazda koyu kalır (B turuncu).",
    control: "select",
    options: [
      { value: "navy", label: "Lacivert (koyu)" },
      { value: "white", label: "Beyaz (açık)" },
    ],
  },
  listing_detail_layout: {
    value: "classic",
    label: "İlan detay düzeni",
    group: "v2",
    description:
      "Özelliklerin konumu. Klasik: fotoğrafların altında ızgara. Sahibinden: fotoğraf ile teklif kartı arasında dikey özellik listesi.",
    control: "select",
    options: [
      { value: "classic", label: "Klasik — özellikler fotoğraf altında" },
      { value: "sahibinden", label: "Sahibinden — özellikler orta kolonda" },
    ],
  },
  recent_sales_placements: {
    value: {
      home: true,
      listing_detail: false,
      profile: false,
      ilanlar: false,
    },
    label: "Son onaylanan satışlar",
    group: "v2",
    description:
      "Sonuçlanan (onaylanan) ilanların kaydırmalı şeridi. Hangi sayfalarda görüneceğini işaretleyin.",
    control: "flagMap",
    options: [
      { value: "home", label: "Ana sayfa (öne çıkanların altı)" },
      { value: "listing_detail", label: "İlan detayı" },
      { value: "profile", label: "Profil / Hesabım" },
      { value: "ilanlar", label: "İlanlar sayfası" },
    ],
  },
  home_insight_sections: {
    value: {
      ending_soon: true,
      most_bids_today: true,
      top_profit: true,
      turkey_map: true,
      live_stats: true,
      for_you: true,
    },
    label: "Ana sayfa istatistik kartları",
    group: "v2",
    description:
      "Öne çıkan vitrin / son satışlar altındaki canlı paneller. İstediğinizi açıp kapatabilirsiniz.",
    control: "flagMap",
    options: [
      { value: "ending_soon", label: "Bitmek üzere olan ilanlar" },
      { value: "most_bids_today", label: "Bugün en çok teklif alanlar" },
      { value: "top_profit", label: "En çok kazandıran satışlar" },
      { value: "turkey_map", label: "Türkiye teklif haritası" },
      { value: "live_stats", label: "Canlı teklif istatistikleri" },
      { value: "for_you", label: "Sana özel öneriler" },
    ],
  },
  premium_verticals_enabled: {
    value: {
      hotel: true,
      logistics: true,
      rideshare: true,
    },
    label: "Premium dikeyler (kapasite)",
    group: "premium",
    description:
      "Otel, lojistik ve yolculuk paylaşımı. Kapalı dikey sidebar ve vitrinde görünmez. Açıkken premium kategoriye tıklanınca yalnızca o dünyanın ilanları listelenir.",
    control: "flagMap",
    options: [
      { value: "hotel", label: "Otel Konaklama" },
      { value: "logistics", label: "Lojistik Taşıma" },
      { value: "rideshare", label: "Yolculuk Paylaşımı" },
    ],
  },
  listing_detail_layout_premium: {
    value: "premium",
    label: "Premium ilan detay düzeni",
    group: "premium",
    description: "Premium (otel/lojistik/yolculuk) ilanlarında kullanılan detay şablonu.",
    control: "select",
    options: [
      { value: "premium", label: "Premium — kapasite odaklı" },
      { value: "sahibinden", label: "Sahibinden kolonlu" },
      { value: "classic", label: "Klasik" },
    ],
  },
  premium_home_limit_hotel: {
    value: 4,
    label: "Premium ana — Otel kartı ilan adedi",
    group: "premium",
    description: "/premium sayfasında Otel Konaklama vitrin kartında kaç ilan gösterilsin.",
    control: "number",
    min: 1,
    max: 12,
  },
  premium_home_limit_logistics: {
    value: 4,
    label: "Premium ana — Lojistik kartı ilan adedi",
    group: "premium",
    description: "/premium sayfasında Lojistik Taşıma vitrin kartında kaç ilan gösterilsin.",
    control: "number",
    min: 1,
    max: 12,
  },
  premium_home_limit_rideshare: {
    value: 4,
    label: "Premium ana — Yolculuk kartı ilan adedi",
    group: "premium",
    description: "/premium sayfasında Yolculuk Paylaşımı vitrin kartında kaç ilan gösterilsin.",
    control: "number",
    min: 1,
    max: 12,
  },

  site_top_belt_banner: {
    value: {
      enabled: false,
      imageUrl: "",
      href: "",
      heightPx: 90,
      widthPx: 0,
    },
    label: "Kuşak üstü boydan boya banner",
    group: "ads",
    description:
      "Header’ın üstünde tam genişlik banner (sahibinden üst şerit). Kapalı varsayılan. Admin → Reklam’dan açılır; yükseklik/genişlik ve tıklanınca gidilecek URL ayarlanır.",
    control: "json",
  },
  site_mid_belt_banner: {
    value: {
      enabled: false,
      imageUrl: "",
      href: "",
      heightPx: 120,
      widthPx: 0,
    },
    label: "Kuşak altı (kartlar üstü) banner",
    group: "ads",
    description:
      "Header / kategori kuşağı ile ilan kartlarının arasında banner. Kapalı varsayılan. Admin → Reklam’dan açılır.",
    control: "json",
  },

  home_promo_banner_height_px: {
    value: 168,
    label: "Üst banner yüksekliği",
    group: "ads",
    description:
      "Ana sayfa orta reklam alanı yüksekliği (px). Banner genişliği 4/5/6 ilan temasına göre otomatik büyür. Yükseklik ve geçiş süresi buradan ayarlanır. JPG, PNG, WEBP ve GIF yüklenebilir.",
    control: "number",
    min: 40,
    max: 420,
    unit: "px",
  },
  home_promo_slide_seconds: {
    value: 5,
    label: "Üst banner slayt süresi",
    group: "ads",
    description: "Üst banner slaytlarının kaç saniyede bir değişeceği.",
    control: "number",
    min: 2,
    max: 60,
    unit: "sn",
  },
  home_sidebar_banner_height_px: {
    value: 148,
    label: "Sağ alt banner yüksekliği",
    group: "ads",
    description:
      "Jeton paketlerinin altındaki sağ alt banner yüksekliği (px). Banner genişliği 4/5/6 ilan temasına göre otomatik büyür. Yükseklik ve geçiş süresi buradan ayarlanır. JPG, PNG, WEBP ve GIF yüklenebilir.",
    control: "number",
    min: 40,
    max: 360,
    unit: "px",
  },
  home_sidebar_slide_seconds: {
    value: 5,
    label: "Sağ alt banner slayt süresi",
    group: "ads",
    description: "Sağ alt banner slaytlarının kaç saniyede bir değişeceği.",
    control: "number",
    min: 2,
    max: 60,
    unit: "sn",
  },

  eids_enabled: {
    value: false,
    label: "EİDS aktif",
    group: "eids",
    description: "Açıkken kapsam kategorilerinde doğrulama altyapısı çalışır.",
    control: "toggle",
  },
  eids_mode: {
    value: "mock",
    label: "EİDS modu",
    group: "eids",
    control: "select",
    options: [
      { value: "mock", label: "Mock (test — engellemez)" },
      { value: "live", label: "Canlı (Bakanlık API)" },
    ],
  },
  eids_categories: {
    value: ["konut", "arac", "isyeri", "arsa", "kiralik"],
    label: "EİDS zorunlu kategoriler",
    group: "eids",
    control: "stringList",
    options: CAT_COST_KEYS.map((c) => ({ value: c.key, label: c.label })),
  },
  eids_badge_text: {
    value:
      "Bu ilan için Ticaret Bakanlığı EİDS (Elektronik İlan Doğrulama Sistemi) yetkilendirmesi yapılmıştır.",
    label: "EİDS rozet metni",
    group: "eids",
    control: "textarea",
  },
  eids_show_badge: {
    value: true,
    label: "Doğrulanmış ilanlarda EİDS yazısını göster",
    group: "eids",
    control: "toggle",
  },
  eids_firma_kodu: {
    value: "",
    label: "Bakanlık firma kodu",
    group: "eids",
    description: "Canlı mod için. Boşsa live bile mock’a düşer.",
    control: "text",
  },
  eids_mock_auto_verify: {
    value: true,
    label: "Mock modda otomatik doğrula",
    group: "eids",
    control: "toggle",
  },

  payment_demo_pos_enabled: {
    value: true,
    label: "Demo sanal POS açık",
    group: "payment",
    description:
      "Açıkken ilan ücreti ödemesi /odeme/demo-pos üzerinden simüle edilir. «Yalnızca jeton» açıksa POS kullanılmaz.",
    control: "toggle",
  },
  payment_tokens_only_enabled: {
    value: false,
    label: "Yalnızca jeton ödemesi (POS kapalı)",
    group: "payment",
    description:
      "Açıkken TL / sanal POS kapanır. İlan ücreti, premium özellikler ve kurumsal paketler yalnızca jetonla ödenir. Paketlerde jeton fiyatı tanımlı olmalıdır. Temel ilan ücreti, hızlı jeton birim fiyatına göre jetona çevrilir (birim 0 ise 1 TL ≈ 1 jeton).",
    control: "toggle",
  },
  revenue_finance: {
    value: {
      vatPercentDefault: 20,
      vatByGroup: {
        listing_fee: 20,
        token: 20,
        shop_subscription: 20,
        other: 20,
      },
      posCommissionPercent: 2.49,
      posFixedFeeTl: 0,
    },
    label: "Gelir KDV / POS komisyon",
    group: "payment",
    description:
      "Gelirler ekranında kullanılan KDV oranları ve POS altyapı komisyonu. Admin → Gelirler sayfasından da düzenlenir.",
    control: "json",
  },
  revenue_expenses: {
    value: [],
    label: "Masraf kayıtları",
    group: "payment",
    description: "Gelirler ekranındaki masraf listesi (JSON). Normalde UI üzerinden eklenir.",
    control: "json",
  },
  payment_pos_provider: {
    value: "demo",
    label: "POS sağlayıcı",
    group: "payment",
    description: "İleride gerçek sanal POS bağlanınca seçilir. Şimdilik yalnızca demo.",
    control: "select",
    options: [
      { value: "demo", label: "Demo POS" },
      { value: "iyzico", label: "iyzico (yakında)" },
      { value: "paytr", label: "PayTR (yakında)" },
    ],
  },
  payment_pos_merchant_id: {
    value: "",
    label: "POS üye işyeri no",
    group: "payment",
    description: "Gerçek POS entegrasyonu için. Demo’da boş bırakılabilir.",
    control: "text",
  },
  payment_pos_api_key: {
    value: "",
    label: "POS API anahtarı",
    group: "payment",
    control: "text",
  },
  payment_pos_secret_key: {
    value: "",
    label: "POS gizli anahtar",
    group: "payment",
    control: "text",
  },
  payment_pos_test_mode: {
    value: true,
    label: "POS test modu",
    group: "payment",
    description: "Canlı POS bağlandığında test/sandbox ortamı.",
    control: "toggle",
  },

  ai_listing_import_enabled: {
    value: false,
    label: "AI ile ilan ekle (profil menüsü)",
    group: "ai",
    description:
      "Açıkken Hesabım → AI ile ilan ekle menüsü görünür. Ekran görüntüsünden alanları okur; jeton düşer.",
    control: "toggle",
  },
  ai_listing_offer_popup_enabled: {
    value: true,
    label: "AI ile ilan ekle popup (İlan Ver)",
    group: "ai",
    description:
      "Açıkken kullanıcı İlan Ver sayfasını açınca “AI ile hızlıca ilan ekle” kampanya popup’ı gösterilir. Kapalıysa yalnızca menüden erişilir.",
    control: "toggle",
  },
  ai_openai_api_key: {
    value: "",
    label: "OpenAI API anahtarı",
    group: "ai",
    description: "sk-... ile başlar. Sadece sunucuda saklanır; tarayıcıya gönderilmez.",
    control: "text",
  },
  ai_openai_base_url: {
    value: "https://api.openai.com/v1",
    label: "OpenAI API taban URL",
    group: "ai",
    description: "Varsayılan OpenAI. Uyumlu proxy kullanıyorsanız burayı değiştirin.",
    control: "text",
  },
  ai_openai_model: {
    value: "gpt-4o",
    label: "Vision model",
    group: "ai",
    description:
      "İlan SS okuma modeli. Öneri: gpt-4o (daha doğru). gpt-4o-mini ucuz ama tik/tablo hataları artar. Vision destekli olmalı.",
    control: "text",
  },
  ai_listing_parse_token_cost: {
    value: 2,
    label: "AI ile ilan ekle — jeton ücreti",
    group: "ai",
    description:
      "Her AI ile ilan okuma işleminde kullanıcından düşülecek jeton. Admin → AI menüsünden değiştirilebilir. 0 = ücretsiz.",
    control: "number",
    min: 0,
    max: 100,
  },

  user_profile_fields: {
    value: {
      firstName: { enabled: true, required: true },
      lastName: { enabled: true, required: true },
      tcKimlik: { enabled: true, required: false },
      birthDate: { enabled: true, required: false },
      email: { enabled: true, required: false },
      phone: { enabled: true, required: false },
      address: { enabled: true, required: false },
      city: { enabled: true, required: false },
      district: { enabled: true, required: false },
      postalCode: { enabled: false, required: false },
      companyName: { enabled: false, required: false },
      taxOffice: { enabled: false, required: false },
      taxNumber: { enabled: false, required: false },
      accountType: { enabled: true, required: true },
      password: { enabled: true, required: false },
    },
    label: "Kullanıcı profil alanları",
    group: "account",
    description:
      "Hesabım → Hesap Ayarları’nda hangi alanların görüneceği. Admin → Kullanıcı Ayarları menüsünden yönetilir. Zorunlu alanlar kayıtta boş bırakılamaz.",
    control: "json",
  },

  escrow_enabled: {
    value: false,
    label: "Güvenli Öde modülü açık",
    group: "escrow",
    description:
      "Açıkken uygun ilanlarda «Güvenli Öde» butonu görünür; ödeme TeklifBu havuzunda tutulur, kargo sonrası satıcıya aktarılır.",
    control: "toggle",
  },
  escrow_pool_name: {
    value: "TeklifBu Güvenli Öde GET Havuzu",
    label: "Havuz hesabı adı",
    group: "escrow",
    description: "Güvenli ödemelerin toplandığı havuz hesabının görünen adı.",
    control: "text",
  },
  escrow_pool_iban: {
    value: "",
    label: "Havuz IBAN",
    group: "escrow",
    description: "Yalnızca admin panelinde görünür. Alıcıya ödeme talimatında gösterilir.",
    control: "text",
  },
  escrow_pool_bank: {
    value: "",
    label: "Havuz banka adı",
    group: "escrow",
    control: "text",
  },
  escrow_commission_percent: {
    value: 0,
    label: "Komisyon (%)",
    group: "escrow",
    description: "Güvenli Öde işlemlerinde satış tutarından kesilecek komisyon yüzdesi.",
    control: "number",
    min: 0,
    max: 30,
    unit: "%",
  },
  escrow_ship_days_options: {
    value: "3,7,10",
    label: "Kargo süresi seçenekleri",
    group: "escrow",
    description: "Satıcıya tanınan gönderim süresi seçenekleri (gün, virgülle ayrılmış).",
    control: "text",
    unit: "gün",
  },
  escrow_default_ship_days: {
    value: 7,
    label: "Varsayılan kargo süresi",
    group: "escrow",
    control: "number",
    min: 1,
    unit: "gün",
  },
  escrow_buyer_confirm_days: {
    value: 3,
    label: "Alıcı onay süresi",
    group: "escrow",
    description: "Teslimat sonrası alıcının ürünü onaylaması için tanınan süre.",
    control: "number",
    min: 1,
    unit: "gün",
  },
  escrow_seller_timeout_action: {
    value: "auto_refund",
    label: "Satıcı süre aşımı",
    group: "escrow",
    description: "Satıcı kargo süresini kaçırırsa uygulanacak kural.",
    control: "select",
    options: [
      { value: "auto_refund", label: "Otomatik alıcıya iade" },
      { value: "open_dispute", label: "Anlaşmazlık aç" },
      { value: "admin_hold", label: "Yönetici bekletsin" },
    ],
  },
  escrow_buyer_timeout_action: {
    value: "auto_release",
    label: "Alıcı onay süresi aşımı",
    group: "escrow",
    description: "Alıcı onay süresini kaçırırsa uygulanacak kural.",
    control: "select",
    options: [
      { value: "auto_release", label: "Otomatik satıcıya öde" },
      { value: "open_dispute", label: "Anlaşmazlık aç" },
      { value: "admin_hold", label: "Yönetici bekletsin" },
    ],
  },
  escrow_require_seller_iban: {
    value: true,
    label: "Satıcı IBAN zorunlu",
    group: "escrow",
    description: "Açıkken IBAN tanımlamayan satıcılar Güvenli Öde ile satış yapamaz.",
    control: "toggle",
  },
  escrow_min_amount_tl: {
    value: 0,
    label: "Minimum tutar",
    group: "escrow",
    control: "number",
    min: 0,
    unit: "TL",
  },
  escrow_max_amount_tl: {
    value: 0,
    label: "Maksimum tutar",
    group: "escrow",
    description: "0 = limitsiz.",
    control: "number",
    min: 0,
    unit: "TL",
  },
  escrow_allow_in_bidding_mode: {
    value: true,
    label: "Teklifli modda da göster",
    group: "escrow",
    description: "Kapalıysa yalnızca Sahibinden Teklifsiz modunda Güvenli Öde butonu görünür.",
    control: "toggle",
  },
  escrow_button_label: {
    value: "Güvenli Öde",
    label: "Buton metni",
    group: "escrow",
    control: "text",
  },
};
